/* tslint:disable */
/* eslint-disable */
/**
 * OpenBook API
 * Beautiful and Engaging Learning Materials
 *
 * The version of the OpenAPI document: 0.0.1-pre1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  PaginatedSubmissionList,
  Submission,
} from '../models/index';
import {
    PaginatedSubmissionListFromJSON,
    PaginatedSubmissionListToJSON,
    SubmissionFromJSON,
    SubmissionToJSON,
} from '../models/index';

export interface CodepeatSubmissionsCreateRequest {
    submission: Omit<Submission, 'id'|'user'|'submitted_at'|'created_at'|'modified_at'>;
    expand?: string;
    fields?: string;
    omit?: string;
}

export interface CodepeatSubmissionsListRequest {
    expand?: string;
    fields?: string;
    omit?: string;
    page?: number;
    pageSize?: number;
    search?: string;
    sort?: string;
    challenge?: string;
    submittedAtDate?: Date;
    submittedAtDateGte?: Date;
    submittedAtDateLte?: Date;
    user?: number;
}

export interface CodepeatSubmissionsRetrieveRequest {
    id: string;
    expand?: string;
    fields?: string;
    omit?: string;
}

/**
 * 
 */
export class CodepeatSubmissionsApi extends runtime.BaseAPI {

    /**
     * Ensure that object permissions are also checked when creating new model instances.  DRF checks object permissions on database-loaded objects, but during creation, the object doesn\'t exist yet. Here we validate the input and construct the instance before saving to allow permission checks.  NOTE: This is a mixin that must be used together with ``ModelViewSet`` to avoid a mysterious circular import in DRF. To overwrite the implementation of ``post()`` the mixin must come first.  Example::      class MyViewSet(ModelViewSetMixin, ModelViewSet):         pass
     * Create
     */
    async codepeatSubmissionsCreateRaw(requestParameters: CodepeatSubmissionsCreateRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Submission>> {
        if (requestParameters['submission'] == null) {
            throw new runtime.RequiredError(
                'submission',
                'Required parameter "submission" was null or undefined when calling codepeatSubmissionsCreate().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['expand'] != null) {
            queryParameters['_expand'] = requestParameters['expand'];
        }

        if (requestParameters['fields'] != null) {
            queryParameters['_fields'] = requestParameters['fields'];
        }

        if (requestParameters['omit'] != null) {
            queryParameters['_omit'] = requestParameters['omit'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["sessionId"] = await this.configuration.apiKey("sessionId"); // SessionAuthentication authentication
        }

        const response = await this.request({
            path: `/api/codepeat/submissions/`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: SubmissionToJSON(requestParameters['submission']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => SubmissionFromJSON(jsonValue));
    }

    /**
     * Ensure that object permissions are also checked when creating new model instances.  DRF checks object permissions on database-loaded objects, but during creation, the object doesn\'t exist yet. Here we validate the input and construct the instance before saving to allow permission checks.  NOTE: This is a mixin that must be used together with ``ModelViewSet`` to avoid a mysterious circular import in DRF. To overwrite the implementation of ``post()`` the mixin must come first.  Example::      class MyViewSet(ModelViewSetMixin, ModelViewSet):         pass
     * Create
     */
    async codepeatSubmissionsCreate(requestParameters: CodepeatSubmissionsCreateRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Submission> {
        const response = await this.codepeatSubmissionsCreateRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Ensure that object permissions are also checked when creating new model instances.  DRF checks object permissions on database-loaded objects, but during creation, the object doesn\'t exist yet. Here we validate the input and construct the instance before saving to allow permission checks.  NOTE: This is a mixin that must be used together with ``ModelViewSet`` to avoid a mysterious circular import in DRF. To overwrite the implementation of ``post()`` the mixin must come first.  Example::      class MyViewSet(ModelViewSetMixin, ModelViewSet):         pass
     * List
     */
    async codepeatSubmissionsListRaw(requestParameters: CodepeatSubmissionsListRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<PaginatedSubmissionList>> {
        const queryParameters: any = {};

        if (requestParameters['expand'] != null) {
            queryParameters['_expand'] = requestParameters['expand'];
        }

        if (requestParameters['fields'] != null) {
            queryParameters['_fields'] = requestParameters['fields'];
        }

        if (requestParameters['omit'] != null) {
            queryParameters['_omit'] = requestParameters['omit'];
        }

        if (requestParameters['page'] != null) {
            queryParameters['_page'] = requestParameters['page'];
        }

        if (requestParameters['pageSize'] != null) {
            queryParameters['_page_size'] = requestParameters['pageSize'];
        }

        if (requestParameters['search'] != null) {
            queryParameters['_search'] = requestParameters['search'];
        }

        if (requestParameters['sort'] != null) {
            queryParameters['_sort'] = requestParameters['sort'];
        }

        if (requestParameters['challenge'] != null) {
            queryParameters['challenge'] = requestParameters['challenge'];
        }

        if (requestParameters['submittedAtDate'] != null) {
            queryParameters['submitted_at__date'] = (requestParameters['submittedAtDate'] as any).toISOString().substring(0,10);
        }

        if (requestParameters['submittedAtDateGte'] != null) {
            queryParameters['submitted_at__date__gte'] = (requestParameters['submittedAtDateGte'] as any).toISOString().substring(0,10);
        }

        if (requestParameters['submittedAtDateLte'] != null) {
            queryParameters['submitted_at__date__lte'] = (requestParameters['submittedAtDateLte'] as any).toISOString().substring(0,10);
        }

        if (requestParameters['user'] != null) {
            queryParameters['user'] = requestParameters['user'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["sessionId"] = await this.configuration.apiKey("sessionId"); // SessionAuthentication authentication
        }

        const response = await this.request({
            path: `/api/codepeat/submissions/`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => PaginatedSubmissionListFromJSON(jsonValue));
    }

    /**
     * Ensure that object permissions are also checked when creating new model instances.  DRF checks object permissions on database-loaded objects, but during creation, the object doesn\'t exist yet. Here we validate the input and construct the instance before saving to allow permission checks.  NOTE: This is a mixin that must be used together with ``ModelViewSet`` to avoid a mysterious circular import in DRF. To overwrite the implementation of ``post()`` the mixin must come first.  Example::      class MyViewSet(ModelViewSetMixin, ModelViewSet):         pass
     * List
     */
    async codepeatSubmissionsList(requestParameters: CodepeatSubmissionsListRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<PaginatedSubmissionList> {
        const response = await this.codepeatSubmissionsListRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Ensure that object permissions are also checked when creating new model instances.  DRF checks object permissions on database-loaded objects, but during creation, the object doesn\'t exist yet. Here we validate the input and construct the instance before saving to allow permission checks.  NOTE: This is a mixin that must be used together with ``ModelViewSet`` to avoid a mysterious circular import in DRF. To overwrite the implementation of ``post()`` the mixin must come first.  Example::      class MyViewSet(ModelViewSetMixin, ModelViewSet):         pass
     * Retrieve
     */
    async codepeatSubmissionsRetrieveRaw(requestParameters: CodepeatSubmissionsRetrieveRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Submission>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling codepeatSubmissionsRetrieve().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['expand'] != null) {
            queryParameters['_expand'] = requestParameters['expand'];
        }

        if (requestParameters['fields'] != null) {
            queryParameters['_fields'] = requestParameters['fields'];
        }

        if (requestParameters['omit'] != null) {
            queryParameters['_omit'] = requestParameters['omit'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["sessionId"] = await this.configuration.apiKey("sessionId"); // SessionAuthentication authentication
        }

        const response = await this.request({
            path: `/api/codepeat/submissions/{id}/`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id']))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => SubmissionFromJSON(jsonValue));
    }

    /**
     * Ensure that object permissions are also checked when creating new model instances.  DRF checks object permissions on database-loaded objects, but during creation, the object doesn\'t exist yet. Here we validate the input and construct the instance before saving to allow permission checks.  NOTE: This is a mixin that must be used together with ``ModelViewSet`` to avoid a mysterious circular import in DRF. To overwrite the implementation of ``post()`` the mixin must come first.  Example::      class MyViewSet(ModelViewSetMixin, ModelViewSet):         pass
     * Retrieve
     */
    async codepeatSubmissionsRetrieve(requestParameters: CodepeatSubmissionsRetrieveRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Submission> {
        const response = await this.codepeatSubmissionsRetrieveRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
