/* tslint:disable */
/* eslint-disable */
/**
 * OpenBook API
 * Beautiful and Engaging Learning Materials
 *
 * The version of the OpenAPI document: 0.0.1-pre1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  AccountActionResult,
  AccountDeletionConfirm,
  AccountDeletionResult,
  AccountDeletionStatus,
  Avatar,
  PasswordChangeConfirm,
  PasswordChangeRequest,
} from '../models/index';
import {
    AccountActionResultFromJSON,
    AccountActionResultToJSON,
    AccountDeletionConfirmFromJSON,
    AccountDeletionConfirmToJSON,
    AccountDeletionResultFromJSON,
    AccountDeletionResultToJSON,
    AccountDeletionStatusFromJSON,
    AccountDeletionStatusToJSON,
    AvatarFromJSON,
    AvatarToJSON,
    PasswordChangeConfirmFromJSON,
    PasswordChangeConfirmToJSON,
    PasswordChangeRequestFromJSON,
    PasswordChangeRequestToJSON,
} from '../models/index';

export interface CodepeatAccountConfirmDeletionCreateRequest {
    accountDeletionConfirm: AccountDeletionConfirm;
}

export interface CodepeatAccountConfirmPasswordChangeCreateRequest {
    passwordChangeConfirm: PasswordChangeConfirm;
}

export interface CodepeatAccountRequestPasswordChangeCreateRequest {
    passwordChangeRequest: PasswordChangeRequest;
}

export interface CodepeatAccountSetAvatarCreateRequest {
    avatar: Avatar;
}

/**
 * 
 */
export class CodepeatAccountApi extends runtime.BaseAPI {

    /**
     * The signed-in user\'s chosen profile picture, or null when none is set.
     * Retrieve
     */
    async codepeatAccountAvatarRetrieveRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Avatar>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["sessionId"] = await this.configuration.apiKey("sessionId"); // SessionAuthentication authentication
        }

        const response = await this.request({
            path: `/api/codepeat/account/avatar/`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => AvatarFromJSON(jsonValue));
    }

    /**
     * The signed-in user\'s chosen profile picture, or null when none is set.
     * Retrieve
     */
    async codepeatAccountAvatarRetrieve(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Avatar> {
        const response = await this.codepeatAccountAvatarRetrieveRaw(initOverrides);
        return await response.value();
    }

    /**
     * Cancel a pending deletion; any outstanding confirmation link becomes invalid.
     * Create
     */
    async codepeatAccountCancelDeletionCreateRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<AccountDeletionStatus>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["sessionId"] = await this.configuration.apiKey("sessionId"); // SessionAuthentication authentication
        }

        const response = await this.request({
            path: `/api/codepeat/account/cancel-deletion/`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => AccountDeletionStatusFromJSON(jsonValue));
    }

    /**
     * Cancel a pending deletion; any outstanding confirmation link becomes invalid.
     * Create
     */
    async codepeatAccountCancelDeletionCreate(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<AccountDeletionStatus> {
        const response = await this.codepeatAccountCancelDeletionCreateRaw(initOverrides);
        return await response.value();
    }

    /**
     * Verify the emailed token and permanently delete the corresponding account.
     * Create
     */
    async codepeatAccountConfirmDeletionCreateRaw(requestParameters: CodepeatAccountConfirmDeletionCreateRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<AccountDeletionResult>> {
        if (requestParameters['accountDeletionConfirm'] == null) {
            throw new runtime.RequiredError(
                'accountDeletionConfirm',
                'Required parameter "accountDeletionConfirm" was null or undefined when calling codepeatAccountConfirmDeletionCreate().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["sessionId"] = await this.configuration.apiKey("sessionId"); // SessionAuthentication authentication
        }

        const response = await this.request({
            path: `/api/codepeat/account/confirm-deletion/`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: AccountDeletionConfirmToJSON(requestParameters['accountDeletionConfirm']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => AccountDeletionResultFromJSON(jsonValue));
    }

    /**
     * Verify the emailed token and permanently delete the corresponding account.
     * Create
     */
    async codepeatAccountConfirmDeletionCreate(requestParameters: CodepeatAccountConfirmDeletionCreateRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<AccountDeletionResult> {
        const response = await this.codepeatAccountConfirmDeletionCreateRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Verify the emailed token and apply the previously staged password.
     * Create
     */
    async codepeatAccountConfirmPasswordChangeCreateRaw(requestParameters: CodepeatAccountConfirmPasswordChangeCreateRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<AccountActionResult>> {
        if (requestParameters['passwordChangeConfirm'] == null) {
            throw new runtime.RequiredError(
                'passwordChangeConfirm',
                'Required parameter "passwordChangeConfirm" was null or undefined when calling codepeatAccountConfirmPasswordChangeCreate().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["sessionId"] = await this.configuration.apiKey("sessionId"); // SessionAuthentication authentication
        }

        const response = await this.request({
            path: `/api/codepeat/account/confirm-password-change/`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: PasswordChangeConfirmToJSON(requestParameters['passwordChangeConfirm']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => AccountActionResultFromJSON(jsonValue));
    }

    /**
     * Verify the emailed token and apply the previously staged password.
     * Create
     */
    async codepeatAccountConfirmPasswordChangeCreate(requestParameters: CodepeatAccountConfirmPasswordChangeCreateRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<AccountActionResult> {
        const response = await this.codepeatAccountConfirmPasswordChangeCreateRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Whether a deletion confirmation is currently pending (drives the profile banner).
     * Retrieve
     */
    async codepeatAccountDeletionStatusRetrieveRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<AccountDeletionStatus>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["sessionId"] = await this.configuration.apiKey("sessionId"); // SessionAuthentication authentication
        }

        const response = await this.request({
            path: `/api/codepeat/account/deletion-status/`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => AccountDeletionStatusFromJSON(jsonValue));
    }

    /**
     * Whether a deletion confirmation is currently pending (drives the profile banner).
     * Retrieve
     */
    async codepeatAccountDeletionStatusRetrieve(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<AccountDeletionStatus> {
        const response = await this.codepeatAccountDeletionStatusRetrieveRaw(initOverrides);
        return await response.value();
    }

    /**
     * (Re-)request deletion: rotate the pending request and email a fresh confirmation link.
     * Create
     */
    async codepeatAccountRequestDeletionCreateRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<AccountDeletionStatus>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["sessionId"] = await this.configuration.apiKey("sessionId"); // SessionAuthentication authentication
        }

        const response = await this.request({
            path: `/api/codepeat/account/request-deletion/`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => AccountDeletionStatusFromJSON(jsonValue));
    }

    /**
     * (Re-)request deletion: rotate the pending request and email a fresh confirmation link.
     * Create
     */
    async codepeatAccountRequestDeletionCreate(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<AccountDeletionStatus> {
        const response = await this.codepeatAccountRequestDeletionCreateRaw(initOverrides);
        return await response.value();
    }

    /**
     * (Re-)request a password change: stage the new (hashed) password and email a confirmation link.
     * Create
     */
    async codepeatAccountRequestPasswordChangeCreateRaw(requestParameters: CodepeatAccountRequestPasswordChangeCreateRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<AccountActionResult>> {
        if (requestParameters['passwordChangeRequest'] == null) {
            throw new runtime.RequiredError(
                'passwordChangeRequest',
                'Required parameter "passwordChangeRequest" was null or undefined when calling codepeatAccountRequestPasswordChangeCreate().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["sessionId"] = await this.configuration.apiKey("sessionId"); // SessionAuthentication authentication
        }

        const response = await this.request({
            path: `/api/codepeat/account/request-password-change/`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: PasswordChangeRequestToJSON(requestParameters['passwordChangeRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => AccountActionResultFromJSON(jsonValue));
    }

    /**
     * (Re-)request a password change: stage the new (hashed) password and email a confirmation link.
     * Create
     */
    async codepeatAccountRequestPasswordChangeCreate(requestParameters: CodepeatAccountRequestPasswordChangeCreateRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<AccountActionResult> {
        const response = await this.codepeatAccountRequestPasswordChangeCreateRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Set (or clear) the signed-in user\'s profile picture from the avatar pool.
     * Create
     */
    async codepeatAccountSetAvatarCreateRaw(requestParameters: CodepeatAccountSetAvatarCreateRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Avatar>> {
        if (requestParameters['avatar'] == null) {
            throw new runtime.RequiredError(
                'avatar',
                'Required parameter "avatar" was null or undefined when calling codepeatAccountSetAvatarCreate().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["sessionId"] = await this.configuration.apiKey("sessionId"); // SessionAuthentication authentication
        }

        const response = await this.request({
            path: `/api/codepeat/account/set-avatar/`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: AvatarToJSON(requestParameters['avatar']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => AvatarFromJSON(jsonValue));
    }

    /**
     * Set (or clear) the signed-in user\'s profile picture from the avatar pool.
     * Create
     */
    async codepeatAccountSetAvatarCreate(requestParameters: CodepeatAccountSetAvatarCreateRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Avatar> {
        const response = await this.codepeatAccountSetAvatarCreateRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
