/* tslint:disable */
/* eslint-disable */
/**
 * OpenBook API
 * Beautiful and Engaging Learning Materials
 *
 * The version of the OpenAPI document: 0.0.1-pre1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  PaginatedSubmissionList,
  Submission,
  SubmissionGradeDecisionEnum,
} from '../models/index';
import {
    PaginatedSubmissionListFromJSON,
    PaginatedSubmissionListToJSON,
    SubmissionFromJSON,
    SubmissionToJSON,
    SubmissionGradeDecisionEnumFromJSON,
    SubmissionGradeDecisionEnumToJSON,
} from '../models/index';

export interface CodepeatSubmissionsCreateRequest {
    challenge: string;
    zipFile: Blob;
    expand?: string;
    fields?: string;
    omit?: string;
}

export interface CodepeatSubmissionsDestroyRequest {
    id: string;
    expand?: string;
    fields?: string;
    omit?: string;
}

export interface CodepeatSubmissionsGradeCreateRequest {
    id: string;
    decision: SubmissionGradeDecisionEnum;
    expand?: string;
    fields?: string;
    omit?: string;
    comment?: string;
}

export interface CodepeatSubmissionsListRequest {
    expand?: string;
    fields?: string;
    omit?: string;
    page?: number;
    pageSize?: number;
    search?: string;
    sort?: string;
    challenge?: string;
    scope?: CodepeatSubmissionsListScopeEnum;
    status?: CodepeatSubmissionsListStatusEnum;
    submittedAtDate?: Date;
    submittedAtDateGte?: Date;
    submittedAtDateLte?: Date;
    user?: number;
}

export interface CodepeatSubmissionsRetrieveRequest {
    id: string;
    expand?: string;
    fields?: string;
    omit?: string;
}

/**
 * 
 */
export class CodepeatSubmissionsApi extends runtime.BaseAPI {

    /**
     * Ensure that object permissions are also checked when creating new model instances.  DRF checks object permissions on database-loaded objects, but during creation, the object doesn\'t exist yet. Here we validate the input and construct the instance before saving to allow permission checks.  NOTE: This is a mixin that must be used together with ``ModelViewSet`` to avoid a mysterious circular import in DRF. To overwrite the implementation of ``post()`` the mixin must come first.  Example::      class MyViewSet(ModelViewSetMixin, ModelViewSet):         pass
     * Create
     */
    async codepeatSubmissionsCreateRaw(requestParameters: CodepeatSubmissionsCreateRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Submission>> {
        if (requestParameters['challenge'] == null) {
            throw new runtime.RequiredError(
                'challenge',
                'Required parameter "challenge" was null or undefined when calling codepeatSubmissionsCreate().'
            );
        }

        if (requestParameters['zipFile'] == null) {
            throw new runtime.RequiredError(
                'zipFile',
                'Required parameter "zipFile" was null or undefined when calling codepeatSubmissionsCreate().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['expand'] != null) {
            queryParameters['_expand'] = requestParameters['expand'];
        }

        if (requestParameters['fields'] != null) {
            queryParameters['_fields'] = requestParameters['fields'];
        }

        if (requestParameters['omit'] != null) {
            queryParameters['_omit'] = requestParameters['omit'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["sessionId"] = await this.configuration.apiKey("sessionId"); // SessionAuthentication authentication
        }

        const consumes: runtime.Consume[] = [
            { contentType: 'multipart/form-data' },
        ];
        // @ts-ignore: canConsumeForm may be unused
        const canConsumeForm = runtime.canConsumeForm(consumes);

        let formParams: { append(param: string, value: any): any };
        let useForm = false;
        // use FormData to transmit files using content-type "multipart/form-data"
        useForm = canConsumeForm;
        if (useForm) {
            formParams = new FormData();
        } else {
            formParams = new URLSearchParams();
        }

        if (requestParameters['challenge'] != null) {
            formParams.append('challenge', requestParameters['challenge'] as any);
        }

        if (requestParameters['zipFile'] != null) {
            formParams.append('zip_file', requestParameters['zipFile'] as any);
        }

        const response = await this.request({
            path: `/api/codepeat/submissions/`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: formParams,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => SubmissionFromJSON(jsonValue));
    }

    /**
     * Ensure that object permissions are also checked when creating new model instances.  DRF checks object permissions on database-loaded objects, but during creation, the object doesn\'t exist yet. Here we validate the input and construct the instance before saving to allow permission checks.  NOTE: This is a mixin that must be used together with ``ModelViewSet`` to avoid a mysterious circular import in DRF. To overwrite the implementation of ``post()`` the mixin must come first.  Example::      class MyViewSet(ModelViewSetMixin, ModelViewSet):         pass
     * Create
     */
    async codepeatSubmissionsCreate(requestParameters: CodepeatSubmissionsCreateRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Submission> {
        const response = await this.codepeatSubmissionsCreateRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Students drop a submission from their own list; a lecturer\'s delete rejects and returns it.
     * Delete
     */
    async codepeatSubmissionsDestroyRaw(requestParameters: CodepeatSubmissionsDestroyRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling codepeatSubmissionsDestroy().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['expand'] != null) {
            queryParameters['_expand'] = requestParameters['expand'];
        }

        if (requestParameters['fields'] != null) {
            queryParameters['_fields'] = requestParameters['fields'];
        }

        if (requestParameters['omit'] != null) {
            queryParameters['_omit'] = requestParameters['omit'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["sessionId"] = await this.configuration.apiKey("sessionId"); // SessionAuthentication authentication
        }

        const response = await this.request({
            path: `/api/codepeat/submissions/{id}/`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id']))),
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Students drop a submission from their own list; a lecturer\'s delete rejects and returns it.
     * Delete
     */
    async codepeatSubmissionsDestroy(requestParameters: CodepeatSubmissionsDestroyRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.codepeatSubmissionsDestroyRaw(requestParameters, initOverrides);
    }

    /**
     * Accept or reject a submission (challenge creator only); an optional comment is stored as feedback.
     * Create
     */
    async codepeatSubmissionsGradeCreateRaw(requestParameters: CodepeatSubmissionsGradeCreateRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Submission>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling codepeatSubmissionsGradeCreate().'
            );
        }

        if (requestParameters['decision'] == null) {
            throw new runtime.RequiredError(
                'decision',
                'Required parameter "decision" was null or undefined when calling codepeatSubmissionsGradeCreate().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['expand'] != null) {
            queryParameters['_expand'] = requestParameters['expand'];
        }

        if (requestParameters['fields'] != null) {
            queryParameters['_fields'] = requestParameters['fields'];
        }

        if (requestParameters['omit'] != null) {
            queryParameters['_omit'] = requestParameters['omit'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["sessionId"] = await this.configuration.apiKey("sessionId"); // SessionAuthentication authentication
        }

        const consumes: runtime.Consume[] = [
            { contentType: 'multipart/form-data' },
            { contentType: 'application/x-www-form-urlencoded' },
            { contentType: 'application/json' },
        ];
        // @ts-ignore: canConsumeForm may be unused
        const canConsumeForm = runtime.canConsumeForm(consumes);

        let formParams: { append(param: string, value: any): any };
        let useForm = false;
        if (useForm) {
            formParams = new FormData();
        } else {
            formParams = new URLSearchParams();
        }

        if (requestParameters['decision'] != null) {
            formParams.append('decision', requestParameters['decision'] as any);
        }

        if (requestParameters['comment'] != null) {
            formParams.append('comment', requestParameters['comment'] as any);
        }

        const response = await this.request({
            path: `/api/codepeat/submissions/{id}/grade/`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id']))),
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: formParams,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => SubmissionFromJSON(jsonValue));
    }

    /**
     * Accept or reject a submission (challenge creator only); an optional comment is stored as feedback.
     * Create
     */
    async codepeatSubmissionsGradeCreate(requestParameters: CodepeatSubmissionsGradeCreateRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Submission> {
        const response = await this.codepeatSubmissionsGradeCreateRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Ensure that object permissions are also checked when creating new model instances.  DRF checks object permissions on database-loaded objects, but during creation, the object doesn\'t exist yet. Here we validate the input and construct the instance before saving to allow permission checks.  NOTE: This is a mixin that must be used together with ``ModelViewSet`` to avoid a mysterious circular import in DRF. To overwrite the implementation of ``post()`` the mixin must come first.  Example::      class MyViewSet(ModelViewSetMixin, ModelViewSet):         pass
     * List
     */
    async codepeatSubmissionsListRaw(requestParameters: CodepeatSubmissionsListRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<PaginatedSubmissionList>> {
        const queryParameters: any = {};

        if (requestParameters['expand'] != null) {
            queryParameters['_expand'] = requestParameters['expand'];
        }

        if (requestParameters['fields'] != null) {
            queryParameters['_fields'] = requestParameters['fields'];
        }

        if (requestParameters['omit'] != null) {
            queryParameters['_omit'] = requestParameters['omit'];
        }

        if (requestParameters['page'] != null) {
            queryParameters['_page'] = requestParameters['page'];
        }

        if (requestParameters['pageSize'] != null) {
            queryParameters['_page_size'] = requestParameters['pageSize'];
        }

        if (requestParameters['search'] != null) {
            queryParameters['_search'] = requestParameters['search'];
        }

        if (requestParameters['sort'] != null) {
            queryParameters['_sort'] = requestParameters['sort'];
        }

        if (requestParameters['challenge'] != null) {
            queryParameters['challenge'] = requestParameters['challenge'];
        }

        if (requestParameters['scope'] != null) {
            queryParameters['scope'] = requestParameters['scope'];
        }

        if (requestParameters['status'] != null) {
            queryParameters['status'] = requestParameters['status'];
        }

        if (requestParameters['submittedAtDate'] != null) {
            queryParameters['submitted_at__date'] = (requestParameters['submittedAtDate'] as any).toISOString().substring(0,10);
        }

        if (requestParameters['submittedAtDateGte'] != null) {
            queryParameters['submitted_at__date__gte'] = (requestParameters['submittedAtDateGte'] as any).toISOString().substring(0,10);
        }

        if (requestParameters['submittedAtDateLte'] != null) {
            queryParameters['submitted_at__date__lte'] = (requestParameters['submittedAtDateLte'] as any).toISOString().substring(0,10);
        }

        if (requestParameters['user'] != null) {
            queryParameters['user'] = requestParameters['user'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["sessionId"] = await this.configuration.apiKey("sessionId"); // SessionAuthentication authentication
        }

        const response = await this.request({
            path: `/api/codepeat/submissions/`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => PaginatedSubmissionListFromJSON(jsonValue));
    }

    /**
     * Ensure that object permissions are also checked when creating new model instances.  DRF checks object permissions on database-loaded objects, but during creation, the object doesn\'t exist yet. Here we validate the input and construct the instance before saving to allow permission checks.  NOTE: This is a mixin that must be used together with ``ModelViewSet`` to avoid a mysterious circular import in DRF. To overwrite the implementation of ``post()`` the mixin must come first.  Example::      class MyViewSet(ModelViewSetMixin, ModelViewSet):         pass
     * List
     */
    async codepeatSubmissionsList(requestParameters: CodepeatSubmissionsListRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<PaginatedSubmissionList> {
        const response = await this.codepeatSubmissionsListRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Ensure that object permissions are also checked when creating new model instances.  DRF checks object permissions on database-loaded objects, but during creation, the object doesn\'t exist yet. Here we validate the input and construct the instance before saving to allow permission checks.  NOTE: This is a mixin that must be used together with ``ModelViewSet`` to avoid a mysterious circular import in DRF. To overwrite the implementation of ``post()`` the mixin must come first.  Example::      class MyViewSet(ModelViewSetMixin, ModelViewSet):         pass
     * Retrieve
     */
    async codepeatSubmissionsRetrieveRaw(requestParameters: CodepeatSubmissionsRetrieveRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Submission>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling codepeatSubmissionsRetrieve().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['expand'] != null) {
            queryParameters['_expand'] = requestParameters['expand'];
        }

        if (requestParameters['fields'] != null) {
            queryParameters['_fields'] = requestParameters['fields'];
        }

        if (requestParameters['omit'] != null) {
            queryParameters['_omit'] = requestParameters['omit'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["sessionId"] = await this.configuration.apiKey("sessionId"); // SessionAuthentication authentication
        }

        const response = await this.request({
            path: `/api/codepeat/submissions/{id}/`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id']))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => SubmissionFromJSON(jsonValue));
    }

    /**
     * Ensure that object permissions are also checked when creating new model instances.  DRF checks object permissions on database-loaded objects, but during creation, the object doesn\'t exist yet. Here we validate the input and construct the instance before saving to allow permission checks.  NOTE: This is a mixin that must be used together with ``ModelViewSet`` to avoid a mysterious circular import in DRF. To overwrite the implementation of ``post()`` the mixin must come first.  Example::      class MyViewSet(ModelViewSetMixin, ModelViewSet):         pass
     * Retrieve
     */
    async codepeatSubmissionsRetrieve(requestParameters: CodepeatSubmissionsRetrieveRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Submission> {
        const response = await this.codepeatSubmissionsRetrieveRaw(requestParameters, initOverrides);
        return await response.value();
    }

}

/**
 * @export
 */
export const CodepeatSubmissionsListScopeEnum = {
    Mine: 'mine',
    ToGrade: 'to_grade'
} as const;
export type CodepeatSubmissionsListScopeEnum = typeof CodepeatSubmissionsListScopeEnum[keyof typeof CodepeatSubmissionsListScopeEnum];
/**
 * @export
 */
export const CodepeatSubmissionsListStatusEnum = {
    Accepted: 'accepted',
    Pending: 'pending',
    Rejected: 'rejected'
} as const;
export type CodepeatSubmissionsListStatusEnum = typeof CodepeatSubmissionsListStatusEnum[keyof typeof CodepeatSubmissionsListStatusEnum];
