/* tslint:disable */
/* eslint-disable */
/**
 * OpenBook API
 * Beautiful and Engaging Learning Materials
 *
 * The version of the OpenAPI document: 0.0.1-pre1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AccountDeletionRequest
 */
export interface AccountDeletionRequest {
    /**
     * 
     * @type {string}
     * @memberof AccountDeletionRequest
     */
    detail: string;
}

/**
 * Check if a given object implements the AccountDeletionRequest interface.
 */
export function instanceOfAccountDeletionRequest(value: object): value is AccountDeletionRequest {
    if (!('detail' in value) || value['detail'] === undefined) return false;
    return true;
}

export function AccountDeletionRequestFromJSON(json: any): AccountDeletionRequest {
    return AccountDeletionRequestFromJSONTyped(json, false);
}

export function AccountDeletionRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): AccountDeletionRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'detail': json['detail'],
    };
}

export function AccountDeletionRequestToJSON(json: any): AccountDeletionRequest {
    return AccountDeletionRequestToJSONTyped(json, false);
}

export function AccountDeletionRequestToJSONTyped(value?: AccountDeletionRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'detail': value['detail'],
    };
}

