/* tslint:disable */
/* eslint-disable */
/**
 * OpenBook API
 * Beautiful and Engaging Learning Materials
 *
 * The version of the OpenAPI document: 0.0.1-pre1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AccountDeletionResult
 */
export interface AccountDeletionResult {
    /**
     * 
     * @type {string}
     * @memberof AccountDeletionResult
     */
    detail: string;
}

/**
 * Check if a given object implements the AccountDeletionResult interface.
 */
export function instanceOfAccountDeletionResult(value: object): value is AccountDeletionResult {
    if (!('detail' in value) || value['detail'] === undefined) return false;
    return true;
}

export function AccountDeletionResultFromJSON(json: any): AccountDeletionResult {
    return AccountDeletionResultFromJSONTyped(json, false);
}

export function AccountDeletionResultFromJSONTyped(json: any, ignoreDiscriminator: boolean): AccountDeletionResult {
    if (json == null) {
        return json;
    }
    return {
        
        'detail': json['detail'],
    };
}

export function AccountDeletionResultToJSON(json: any): AccountDeletionResult {
    return AccountDeletionResultToJSONTyped(json, false);
}

export function AccountDeletionResultToJSONTyped(value?: AccountDeletionResult | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'detail': value['detail'],
    };
}

