/* tslint:disable */
/* eslint-disable */
/**
 * OpenBook API
 * Beautiful and Engaging Learning Materials
 *
 * The version of the OpenAPI document: 0.0.1-pre1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AccountDeletionConfirm
 */
export interface AccountDeletionConfirm {
    /**
     * 
     * @type {string}
     * @memberof AccountDeletionConfirm
     */
    token: string;
}

/**
 * Check if a given object implements the AccountDeletionConfirm interface.
 */
export function instanceOfAccountDeletionConfirm(value: object): value is AccountDeletionConfirm {
    if (!('token' in value) || value['token'] === undefined) return false;
    return true;
}

export function AccountDeletionConfirmFromJSON(json: any): AccountDeletionConfirm {
    return AccountDeletionConfirmFromJSONTyped(json, false);
}

export function AccountDeletionConfirmFromJSONTyped(json: any, ignoreDiscriminator: boolean): AccountDeletionConfirm {
    if (json == null) {
        return json;
    }
    return {
        
        'token': json['token'],
    };
}

export function AccountDeletionConfirmToJSON(json: any): AccountDeletionConfirm {
    return AccountDeletionConfirmToJSONTyped(json, false);
}

export function AccountDeletionConfirmToJSONTyped(value?: AccountDeletionConfirm | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'token': value['token'],
    };
}

