/* tslint:disable */
/* eslint-disable */
/**
 * OpenBook API
 * Beautiful and Engaging Learning Materials
 *
 * The version of the OpenAPI document: 0.0.1-pre1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AccountDeletionStatus
 */
export interface AccountDeletionStatus {
    /**
     * 
     * @type {boolean}
     * @memberof AccountDeletionStatus
     */
    pending: boolean;
}

/**
 * Check if a given object implements the AccountDeletionStatus interface.
 */
export function instanceOfAccountDeletionStatus(value: object): value is AccountDeletionStatus {
    if (!('pending' in value) || value['pending'] === undefined) return false;
    return true;
}

export function AccountDeletionStatusFromJSON(json: any): AccountDeletionStatus {
    return AccountDeletionStatusFromJSONTyped(json, false);
}

export function AccountDeletionStatusFromJSONTyped(json: any, ignoreDiscriminator: boolean): AccountDeletionStatus {
    if (json == null) {
        return json;
    }
    return {
        
        'pending': json['pending'],
    };
}

export function AccountDeletionStatusToJSON(json: any): AccountDeletionStatus {
    return AccountDeletionStatusToJSONTyped(json, false);
}

export function AccountDeletionStatusToJSONTyped(value?: AccountDeletionStatus | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'pending': value['pending'],
    };
}

