/* tslint:disable */
/* eslint-disable */
/**
 * OpenBook API
 * Beautiful and Engaging Learning Materials
 *
 * The version of the OpenAPI document: 0.0.1-pre1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * A profile picture: the relative path of an image from the CodePeat avatar pool.
 * @export
 * @interface Avatar
 */
export interface Avatar {
    /**
     * 
     * @type {string}
     * @memberof Avatar
     */
    avatar: string | null;
}

/**
 * Check if a given object implements the Avatar interface.
 */
export function instanceOfAvatar(value: object): value is Avatar {
    if (!('avatar' in value) || value['avatar'] === undefined) return false;
    return true;
}

export function AvatarFromJSON(json: any): Avatar {
    return AvatarFromJSONTyped(json, false);
}

export function AvatarFromJSONTyped(json: any, ignoreDiscriminator: boolean): Avatar {
    if (json == null) {
        return json;
    }
    return {
        
        'avatar': json['avatar'],
    };
}

export function AvatarToJSON(json: any): Avatar {
    return AvatarToJSONTyped(json, false);
}

export function AvatarToJSONTyped(value?: Avatar | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'avatar': value['avatar'],
    };
}

