/* tslint:disable */
/* eslint-disable */
/**
 * OpenBook API
 * Beautiful and Engaging Learning Materials
 *
 * The version of the OpenAPI document: 0.0.1-pre1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ChallengeFavoriteResult
 */
export interface ChallengeFavoriteResult {
    /**
     * 
     * @type {boolean}
     * @memberof ChallengeFavoriteResult
     */
    favorited: boolean;
}

/**
 * Check if a given object implements the ChallengeFavoriteResult interface.
 */
export function instanceOfChallengeFavoriteResult(value: object): value is ChallengeFavoriteResult {
    if (!('favorited' in value) || value['favorited'] === undefined) return false;
    return true;
}

export function ChallengeFavoriteResultFromJSON(json: any): ChallengeFavoriteResult {
    return ChallengeFavoriteResultFromJSONTyped(json, false);
}

export function ChallengeFavoriteResultFromJSONTyped(json: any, ignoreDiscriminator: boolean): ChallengeFavoriteResult {
    if (json == null) {
        return json;
    }
    return {
        
        'favorited': json['favorited'],
    };
}

export function ChallengeFavoriteResultToJSON(json: any): ChallengeFavoriteResult {
    return ChallengeFavoriteResultToJSONTyped(json, false);
}

export function ChallengeFavoriteResultToJSONTyped(value?: ChallengeFavoriteResult | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'favorited': value['favorited'],
    };
}

