/* tslint:disable */
/* eslint-disable */
/**
 * OpenBook API
 * Beautiful and Engaging Learning Materials
 *
 * The version of the OpenAPI document: 0.0.1-pre1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ChallengeCanCreate
 */
export interface ChallengeCanCreate {
    /**
     * 
     * @type {boolean}
     * @memberof ChallengeCanCreate
     */
    canCreate: boolean;
}

/**
 * Check if a given object implements the ChallengeCanCreate interface.
 */
export function instanceOfChallengeCanCreate(value: object): value is ChallengeCanCreate {
    if (!('canCreate' in value) || value['canCreate'] === undefined) return false;
    return true;
}

export function ChallengeCanCreateFromJSON(json: any): ChallengeCanCreate {
    return ChallengeCanCreateFromJSONTyped(json, false);
}

export function ChallengeCanCreateFromJSONTyped(json: any, ignoreDiscriminator: boolean): ChallengeCanCreate {
    if (json == null) {
        return json;
    }
    return {
        
        'canCreate': json['can_create'],
    };
}

export function ChallengeCanCreateToJSON(json: any): ChallengeCanCreate {
    return ChallengeCanCreateToJSONTyped(json, false);
}

export function ChallengeCanCreateToJSONTyped(value?: ChallengeCanCreate | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'can_create': value['canCreate'],
    };
}

