/* tslint:disable */
/* eslint-disable */
/**
 * OpenBook API
 * Beautiful and Engaging Learning Materials
 *
 * The version of the OpenAPI document: 0.0.1-pre1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ChallengeInviteLink
 */
export interface ChallengeInviteLink {
    /**
     * 
     * @type {string}
     * @memberof ChallengeInviteLink
     */
    url: string;
    /**
     * 
     * @type {number}
     * @memberof ChallengeInviteLink
     */
    expiresIn: number;
}

/**
 * Check if a given object implements the ChallengeInviteLink interface.
 */
export function instanceOfChallengeInviteLink(value: object): value is ChallengeInviteLink {
    if (!('url' in value) || value['url'] === undefined) return false;
    if (!('expiresIn' in value) || value['expiresIn'] === undefined) return false;
    return true;
}

export function ChallengeInviteLinkFromJSON(json: any): ChallengeInviteLink {
    return ChallengeInviteLinkFromJSONTyped(json, false);
}

export function ChallengeInviteLinkFromJSONTyped(json: any, ignoreDiscriminator: boolean): ChallengeInviteLink {
    if (json == null) {
        return json;
    }
    return {
        
        'url': json['url'],
        'expiresIn': json['expires_in'],
    };
}

export function ChallengeInviteLinkToJSON(json: any): ChallengeInviteLink {
    return ChallengeInviteLinkToJSONTyped(json, false);
}

export function ChallengeInviteLinkToJSONTyped(value?: ChallengeInviteLink | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'url': value['url'],
        'expires_in': value['expiresIn'],
    };
}

