/* tslint:disable */
/* eslint-disable */
/**
 * OpenBook API
 * Beautiful and Engaging Learning Materials
 *
 * The version of the OpenAPI document: 0.0.1-pre1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * * `easy` - Easy
 * * `medium` - Medium
 * * `hard` - Hard
 * @export
 */
export const DifficultyEnum = {
    Easy: 'easy',
    Medium: 'medium',
    Hard: 'hard'
} as const;
export type DifficultyEnum = typeof DifficultyEnum[keyof typeof DifficultyEnum];


export function instanceOfDifficultyEnum(value: any): boolean {
    for (const key in DifficultyEnum) {
        if (Object.prototype.hasOwnProperty.call(DifficultyEnum, key)) {
            if (DifficultyEnum[key as keyof typeof DifficultyEnum] === value) {
                return true;
            }
        }
    }
    return false;
}

export function DifficultyEnumFromJSON(json: any): DifficultyEnum {
    return DifficultyEnumFromJSONTyped(json, false);
}

export function DifficultyEnumFromJSONTyped(json: any, ignoreDiscriminator: boolean): DifficultyEnum {
    return json as DifficultyEnum;
}

export function DifficultyEnumToJSON(value?: DifficultyEnum | null): any {
    return value as any;
}

export function DifficultyEnumToJSONTyped(value: any, ignoreDiscriminator: boolean): DifficultyEnum {
    return value as DifficultyEnum;
}

