/* tslint:disable */
/* eslint-disable */
/**
 * OpenBook API
 * Beautiful and Engaging Learning Materials
 *
 * The version of the OpenAPI document: 0.0.1-pre1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Reuse full cleaning and validation logic of the models in the REST API.
 * 
 * Reuse ``full_clean()``, ``clean()``, field validation, and uniqueness checks.
 * Also make sure that the pre-filled model instance can be accessed in the DRF view.
 * @export
 * @interface Feedback
 */
export interface Feedback {
    /**
     * 
     * @type {string}
     * @memberof Feedback
     */
    readonly id: string;
    /**
     * 
     * @type {string}
     * @memberof Feedback
     */
    submission: string;
    /**
     * 
     * @type {number}
     * @memberof Feedback
     */
    lecturer: number;
    /**
     * 
     * @type {string}
     * @memberof Feedback
     */
    comments?: string;
    /**
     * 
     * @type {Date}
     * @memberof Feedback
     */
    readonly createdAt: Date | null;
    /**
     * 
     * @type {Date}
     * @memberof Feedback
     */
    readonly modifiedAt: Date | null;
}

/**
 * Check if a given object implements the Feedback interface.
 */
export function instanceOfFeedback(value: object): value is Feedback {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('submission' in value) || value['submission'] === undefined) return false;
    if (!('lecturer' in value) || value['lecturer'] === undefined) return false;
    if (!('createdAt' in value) || value['createdAt'] === undefined) return false;
    if (!('modifiedAt' in value) || value['modifiedAt'] === undefined) return false;
    return true;
}

export function FeedbackFromJSON(json: any): Feedback {
    return FeedbackFromJSONTyped(json, false);
}

export function FeedbackFromJSONTyped(json: any, ignoreDiscriminator: boolean): Feedback {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'submission': json['submission'],
        'lecturer': json['lecturer'],
        'comments': json['comments'] == null ? undefined : json['comments'],
        'createdAt': (json['created_at'] == null ? null : new Date(json['created_at'])),
        'modifiedAt': (json['modified_at'] == null ? null : new Date(json['modified_at'])),
    };
}

export function FeedbackToJSON(json: any): Feedback {
    return FeedbackToJSONTyped(json, false);
}

export function FeedbackToJSONTyped(value?: Omit<Feedback, 'id'|'created_at'|'modified_at'> | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'submission': value['submission'],
        'lecturer': value['lecturer'],
        'comments': value['comments'],
    };
}

