/* tslint:disable */
/* eslint-disable */
/**
 * OpenBook API
 * Beautiful and Engaging Learning Materials
 *
 * The version of the OpenAPI document: 0.0.1-pre1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { SlugEnum } from './SlugEnum';
import {
    SlugEnumFromJSON,
    SlugEnumFromJSONTyped,
    SlugEnumToJSON,
    SlugEnumToJSONTyped,
} from './SlugEnum';

/**
 * Reuse full cleaning and validation logic of the models in the REST API.
 * 
 * Reuse ``full_clean()``, ``clean()``, field validation, and uniqueness checks.
 * Also make sure that the pre-filled model instance can be accessed in the DRF view.
 * @export
 * @interface LegalDocument
 */
export interface LegalDocument {
    /**
     * 
     * @type {string}
     * @memberof LegalDocument
     */
    readonly id: string;
    /**
     * 
     * @type {SlugEnum}
     * @memberof LegalDocument
     */
    readonly slug: SlugEnum;
    /**
     * 
     * @type {string}
     * @memberof LegalDocument
     */
    content?: string;
    /**
     * 
     * @type {boolean}
     * @memberof LegalDocument
     */
    readonly canEdit: boolean;
    /**
     * 
     * @type {Date}
     * @memberof LegalDocument
     */
    readonly createdAt: Date | null;
    /**
     * 
     * @type {Date}
     * @memberof LegalDocument
     */
    readonly modifiedAt: Date | null;
}



/**
 * Check if a given object implements the LegalDocument interface.
 */
export function instanceOfLegalDocument(value: object): value is LegalDocument {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('slug' in value) || value['slug'] === undefined) return false;
    if (!('canEdit' in value) || value['canEdit'] === undefined) return false;
    if (!('createdAt' in value) || value['createdAt'] === undefined) return false;
    if (!('modifiedAt' in value) || value['modifiedAt'] === undefined) return false;
    return true;
}

export function LegalDocumentFromJSON(json: any): LegalDocument {
    return LegalDocumentFromJSONTyped(json, false);
}

export function LegalDocumentFromJSONTyped(json: any, ignoreDiscriminator: boolean): LegalDocument {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'slug': SlugEnumFromJSON(json['slug']),
        'content': json['content'] == null ? undefined : json['content'],
        'canEdit': json['can_edit'],
        'createdAt': (json['created_at'] == null ? null : new Date(json['created_at'])),
        'modifiedAt': (json['modified_at'] == null ? null : new Date(json['modified_at'])),
    };
}

export function LegalDocumentToJSON(json: any): LegalDocument {
    return LegalDocumentToJSONTyped(json, false);
}

export function LegalDocumentToJSONTyped(value?: Omit<LegalDocument, 'id'|'slug'|'can_edit'|'created_at'|'modified_at'> | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'content': value['content'],
    };
}

