/* tslint:disable */
/* eslint-disable */
/**
 * OpenBook API
 * Beautiful and Engaging Learning Materials
 *
 * The version of the OpenAPI document: 0.0.1-pre1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ReflectionQuestion } from './ReflectionQuestion';
import {
    ReflectionQuestionFromJSON,
    ReflectionQuestionFromJSONTyped,
    ReflectionQuestionToJSON,
    ReflectionQuestionToJSONTyped,
} from './ReflectionQuestion';

/**
 * 
 * @export
 * @interface PaginatedReflectionQuestionList
 */
export interface PaginatedReflectionQuestionList {
    /**
     * 
     * @type {number}
     * @memberof PaginatedReflectionQuestionList
     */
    count: number;
    /**
     * 
     * @type {string}
     * @memberof PaginatedReflectionQuestionList
     */
    next?: string | null;
    /**
     * 
     * @type {string}
     * @memberof PaginatedReflectionQuestionList
     */
    previous?: string | null;
    /**
     * 
     * @type {Array<ReflectionQuestion>}
     * @memberof PaginatedReflectionQuestionList
     */
    results: Array<ReflectionQuestion>;
}

/**
 * Check if a given object implements the PaginatedReflectionQuestionList interface.
 */
export function instanceOfPaginatedReflectionQuestionList(value: object): value is PaginatedReflectionQuestionList {
    if (!('count' in value) || value['count'] === undefined) return false;
    if (!('results' in value) || value['results'] === undefined) return false;
    return true;
}

export function PaginatedReflectionQuestionListFromJSON(json: any): PaginatedReflectionQuestionList {
    return PaginatedReflectionQuestionListFromJSONTyped(json, false);
}

export function PaginatedReflectionQuestionListFromJSONTyped(json: any, ignoreDiscriminator: boolean): PaginatedReflectionQuestionList {
    if (json == null) {
        return json;
    }
    return {
        
        'count': json['count'],
        'next': json['next'] == null ? undefined : json['next'],
        'previous': json['previous'] == null ? undefined : json['previous'],
        'results': ((json['results'] as Array<any>).map(ReflectionQuestionFromJSON)),
    };
}

export function PaginatedReflectionQuestionListToJSON(json: any): PaginatedReflectionQuestionList {
    return PaginatedReflectionQuestionListToJSONTyped(json, false);
}

export function PaginatedReflectionQuestionListToJSONTyped(value?: PaginatedReflectionQuestionList | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'count': value['count'],
        'next': value['next'],
        'previous': value['previous'],
        'results': ((value['results'] as Array<any>).map(ReflectionQuestionToJSON)),
    };
}

