/* tslint:disable */
/* eslint-disable */
/**
 * OpenBook API
 * Beautiful and Engaging Learning Materials
 *
 * The version of the OpenAPI document: 0.0.1-pre1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { LegalDocument } from './LegalDocument';
import {
    LegalDocumentFromJSON,
    LegalDocumentFromJSONTyped,
    LegalDocumentToJSON,
    LegalDocumentToJSONTyped,
} from './LegalDocument';

/**
 * 
 * @export
 * @interface PaginatedLegalDocumentList
 */
export interface PaginatedLegalDocumentList {
    /**
     * 
     * @type {number}
     * @memberof PaginatedLegalDocumentList
     */
    count: number;
    /**
     * 
     * @type {string}
     * @memberof PaginatedLegalDocumentList
     */
    next?: string | null;
    /**
     * 
     * @type {string}
     * @memberof PaginatedLegalDocumentList
     */
    previous?: string | null;
    /**
     * 
     * @type {Array<LegalDocument>}
     * @memberof PaginatedLegalDocumentList
     */
    results: Array<LegalDocument>;
}

/**
 * Check if a given object implements the PaginatedLegalDocumentList interface.
 */
export function instanceOfPaginatedLegalDocumentList(value: object): value is PaginatedLegalDocumentList {
    if (!('count' in value) || value['count'] === undefined) return false;
    if (!('results' in value) || value['results'] === undefined) return false;
    return true;
}

export function PaginatedLegalDocumentListFromJSON(json: any): PaginatedLegalDocumentList {
    return PaginatedLegalDocumentListFromJSONTyped(json, false);
}

export function PaginatedLegalDocumentListFromJSONTyped(json: any, ignoreDiscriminator: boolean): PaginatedLegalDocumentList {
    if (json == null) {
        return json;
    }
    return {
        
        'count': json['count'],
        'next': json['next'] == null ? undefined : json['next'],
        'previous': json['previous'] == null ? undefined : json['previous'],
        'results': ((json['results'] as Array<any>).map(LegalDocumentFromJSON)),
    };
}

export function PaginatedLegalDocumentListToJSON(json: any): PaginatedLegalDocumentList {
    return PaginatedLegalDocumentListToJSONTyped(json, false);
}

export function PaginatedLegalDocumentListToJSONTyped(value?: PaginatedLegalDocumentList | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'count': value['count'],
        'next': value['next'],
        'previous': value['previous'],
        'results': ((value['results'] as Array<any>).map(LegalDocumentToJSON)),
    };
}

