/* tslint:disable */
/* eslint-disable */
/**
 * OpenBook API
 * Beautiful and Engaging Learning Materials
 *
 * The version of the OpenAPI document: 0.0.1-pre1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PasswordChangeConfirm
 */
export interface PasswordChangeConfirm {
    /**
     * 
     * @type {string}
     * @memberof PasswordChangeConfirm
     */
    token: string;
}

/**
 * Check if a given object implements the PasswordChangeConfirm interface.
 */
export function instanceOfPasswordChangeConfirm(value: object): value is PasswordChangeConfirm {
    if (!('token' in value) || value['token'] === undefined) return false;
    return true;
}

export function PasswordChangeConfirmFromJSON(json: any): PasswordChangeConfirm {
    return PasswordChangeConfirmFromJSONTyped(json, false);
}

export function PasswordChangeConfirmFromJSONTyped(json: any, ignoreDiscriminator: boolean): PasswordChangeConfirm {
    if (json == null) {
        return json;
    }
    return {
        
        'token': json['token'],
    };
}

export function PasswordChangeConfirmToJSON(json: any): PasswordChangeConfirm {
    return PasswordChangeConfirmToJSONTyped(json, false);
}

export function PasswordChangeConfirmToJSONTyped(value?: PasswordChangeConfirm | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'token': value['token'],
    };
}

