/* tslint:disable */
/* eslint-disable */
/**
 * OpenBook API
 * Beautiful and Engaging Learning Materials
 *
 * The version of the OpenAPI document: 0.0.1-pre1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Documents the create request as multipart with just the writable fields (the full
 * serializer accepts the same input; this only keeps the generated client clean).
 * @export
 * @interface SubmissionCreate
 */
export interface SubmissionCreate {
    /**
     * 
     * @type {string}
     * @memberof SubmissionCreate
     */
    challenge: string;
    /**
     * 
     * @type {string}
     * @memberof SubmissionCreate
     */
    zipFile: string;
}

/**
 * Check if a given object implements the SubmissionCreate interface.
 */
export function instanceOfSubmissionCreate(value: object): value is SubmissionCreate {
    if (!('challenge' in value) || value['challenge'] === undefined) return false;
    if (!('zipFile' in value) || value['zipFile'] === undefined) return false;
    return true;
}

export function SubmissionCreateFromJSON(json: any): SubmissionCreate {
    return SubmissionCreateFromJSONTyped(json, false);
}

export function SubmissionCreateFromJSONTyped(json: any, ignoreDiscriminator: boolean): SubmissionCreate {
    if (json == null) {
        return json;
    }
    return {
        
        'challenge': json['challenge'],
        'zipFile': json['zip_file'],
    };
}

export function SubmissionCreateToJSON(json: any): SubmissionCreate {
    return SubmissionCreateToJSONTyped(json, false);
}

export function SubmissionCreateToJSONTyped(value?: SubmissionCreate | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'challenge': value['challenge'],
        'zip_file': value['zipFile'],
    };
}

