/* tslint:disable */
/* eslint-disable */
/**
 * OpenBook API
 * Beautiful and Engaging Learning Materials
 *
 * The version of the OpenAPI document: 0.0.1-pre1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * * `accept` - accept
 * * `reject` - reject
 * @export
 */
export const SubmissionGradeDecisionEnum = {
    Accept: 'accept',
    Reject: 'reject'
} as const;
export type SubmissionGradeDecisionEnum = typeof SubmissionGradeDecisionEnum[keyof typeof SubmissionGradeDecisionEnum];


export function instanceOfSubmissionGradeDecisionEnum(value: any): boolean {
    for (const key in SubmissionGradeDecisionEnum) {
        if (Object.prototype.hasOwnProperty.call(SubmissionGradeDecisionEnum, key)) {
            if (SubmissionGradeDecisionEnum[key as keyof typeof SubmissionGradeDecisionEnum] === value) {
                return true;
            }
        }
    }
    return false;
}

export function SubmissionGradeDecisionEnumFromJSON(json: any): SubmissionGradeDecisionEnum {
    return SubmissionGradeDecisionEnumFromJSONTyped(json, false);
}

export function SubmissionGradeDecisionEnumFromJSONTyped(json: any, ignoreDiscriminator: boolean): SubmissionGradeDecisionEnum {
    return json as SubmissionGradeDecisionEnum;
}

export function SubmissionGradeDecisionEnumToJSON(value?: SubmissionGradeDecisionEnum | null): any {
    return value as any;
}

export function SubmissionGradeDecisionEnumToJSONTyped(value: any, ignoreDiscriminator: boolean): SubmissionGradeDecisionEnum {
    return value as SubmissionGradeDecisionEnum;
}

