/* tslint:disable */
/* eslint-disable */
/**
 * OpenBook API
 * Beautiful and Engaging Learning Materials
 *
 * The version of the OpenAPI document: 0.0.1-pre1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * * `pending` - Pending
 * * `passed` - Passed
 * * `failed` - Failed
 * * `error` - Error
 * @export
 */
export const TestResultStatusEnum = {
    Pending: 'pending',
    Passed: 'passed',
    Failed: 'failed',
    Error: 'error'
} as const;
export type TestResultStatusEnum = typeof TestResultStatusEnum[keyof typeof TestResultStatusEnum];


export function instanceOfTestResultStatusEnum(value: any): boolean {
    for (const key in TestResultStatusEnum) {
        if (Object.prototype.hasOwnProperty.call(TestResultStatusEnum, key)) {
            if (TestResultStatusEnum[key as keyof typeof TestResultStatusEnum] === value) {
                return true;
            }
        }
    }
    return false;
}

export function TestResultStatusEnumFromJSON(json: any): TestResultStatusEnum {
    return TestResultStatusEnumFromJSONTyped(json, false);
}

export function TestResultStatusEnumFromJSONTyped(json: any, ignoreDiscriminator: boolean): TestResultStatusEnum {
    return json as TestResultStatusEnum;
}

export function TestResultStatusEnumToJSON(value?: TestResultStatusEnum | null): any {
    return value as any;
}

export function TestResultStatusEnumToJSONTyped(value: any, ignoreDiscriminator: boolean): TestResultStatusEnum {
    return value as TestResultStatusEnum;
}

