/* tslint:disable */
/* eslint-disable */
/**
 * OpenBook API
 * Beautiful and Engaging Learning Materials
 *
 * The version of the OpenAPI document: 0.0.1-pre1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { StatusEnum } from './StatusEnum';
import {
    StatusEnumFromJSON,
    StatusEnumFromJSONTyped,
    StatusEnumToJSON,
    StatusEnumToJSONTyped,
} from './StatusEnum';

/**
 * Reuse full cleaning and validation logic of the models in the REST API.
 * 
 * Reuse ``full_clean()``, ``clean()``, field validation, and uniqueness checks.
 * Also make sure that the pre-filled model instance can be accessed in the DRF view.
 * @export
 * @interface TestResult
 */
export interface TestResult {
    /**
     * 
     * @type {string}
     * @memberof TestResult
     */
    readonly id: string;
    /**
     * 
     * @type {string}
     * @memberof TestResult
     */
    submission: string;
    /**
     * 
     * @type {StatusEnum}
     * @memberof TestResult
     */
    status?: StatusEnum;
    /**
     * 
     * @type {string}
     * @memberof TestResult
     */
    output: string;
    /**
     * 
     * @type {Date}
     * @memberof TestResult
     */
    readonly createdAt: Date | null;
    /**
     * 
     * @type {Date}
     * @memberof TestResult
     */
    readonly modifiedAt: Date | null;
}



/**
 * Check if a given object implements the TestResult interface.
 */
export function instanceOfTestResult(value: object): value is TestResult {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('submission' in value) || value['submission'] === undefined) return false;
    if (!('output' in value) || value['output'] === undefined) return false;
    if (!('createdAt' in value) || value['createdAt'] === undefined) return false;
    if (!('modifiedAt' in value) || value['modifiedAt'] === undefined) return false;
    return true;
}

export function TestResultFromJSON(json: any): TestResult {
    return TestResultFromJSONTyped(json, false);
}

export function TestResultFromJSONTyped(json: any, ignoreDiscriminator: boolean): TestResult {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'submission': json['submission'],
        'status': json['status'] == null ? undefined : StatusEnumFromJSON(json['status']),
        'output': json['output'],
        'createdAt': (json['created_at'] == null ? null : new Date(json['created_at'])),
        'modifiedAt': (json['modified_at'] == null ? null : new Date(json['modified_at'])),
    };
}

export function TestResultToJSON(json: any): TestResult {
    return TestResultToJSONTyped(json, false);
}

export function TestResultToJSONTyped(value?: Omit<TestResult, 'id'|'created_at'|'modified_at'> | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'submission': value['submission'],
        'status': StatusEnumToJSON(value['status']),
        'output': value['output'],
    };
}

