/* tslint:disable */
/* eslint-disable */
/**
 * OpenBook API
 * Beautiful and Engaging Learning Materials
 *
 * The version of the OpenAPI document: 0.0.1-pre1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UserProgress
 */
export interface UserProgress {
    /**
     * 
     * @type {number}
     * @memberof UserProgress
     */
    xp: number;
    /**
     * 
     * @type {number}
     * @memberof UserProgress
     */
    level: number;
    /**
     * 
     * @type {number}
     * @memberof UserProgress
     */
    xpIntoLevel: number;
    /**
     * 
     * @type {number}
     * @memberof UserProgress
     */
    xpForNextLevel: number;
}

/**
 * Check if a given object implements the UserProgress interface.
 */
export function instanceOfUserProgress(value: object): value is UserProgress {
    if (!('xp' in value) || value['xp'] === undefined) return false;
    if (!('level' in value) || value['level'] === undefined) return false;
    if (!('xpIntoLevel' in value) || value['xpIntoLevel'] === undefined) return false;
    if (!('xpForNextLevel' in value) || value['xpForNextLevel'] === undefined) return false;
    return true;
}

export function UserProgressFromJSON(json: any): UserProgress {
    return UserProgressFromJSONTyped(json, false);
}

export function UserProgressFromJSONTyped(json: any, ignoreDiscriminator: boolean): UserProgress {
    if (json == null) {
        return json;
    }
    return {
        
        'xp': json['xp'],
        'level': json['level'],
        'xpIntoLevel': json['xp_into_level'],
        'xpForNextLevel': json['xp_for_next_level'],
    };
}

export function UserProgressToJSON(json: any): UserProgress {
    return UserProgressToJSONTyped(json, false);
}

export function UserProgressToJSONTyped(value?: UserProgress | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'xp': value['xp'],
        'level': value['level'],
        'xp_into_level': value['xpIntoLevel'],
        'xp_for_next_level': value['xpForNextLevel'],
    };
}

