/* tslint:disable */
/* eslint-disable */
/**
 * OpenBook API
 * Beautiful and Engaging Learning Materials
 *
 * The version of the OpenAPI document: 0.0.1-pre1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * * `public` - Public
 * * `private` - Private
 * @export
 */
export const VisibilityEnum = {
    Public: 'public',
    Private: 'private'
} as const;
export type VisibilityEnum = typeof VisibilityEnum[keyof typeof VisibilityEnum];


export function instanceOfVisibilityEnum(value: any): boolean {
    for (const key in VisibilityEnum) {
        if (Object.prototype.hasOwnProperty.call(VisibilityEnum, key)) {
            if (VisibilityEnum[key as keyof typeof VisibilityEnum] === value) {
                return true;
            }
        }
    }
    return false;
}

export function VisibilityEnumFromJSON(json: any): VisibilityEnum {
    return VisibilityEnumFromJSONTyped(json, false);
}

export function VisibilityEnumFromJSONTyped(json: any, ignoreDiscriminator: boolean): VisibilityEnum {
    return json as VisibilityEnum;
}

export function VisibilityEnumToJSON(value?: VisibilityEnum | null): any {
    return value as any;
}

export function VisibilityEnumToJSONTyped(value: any, ignoreDiscriminator: boolean): VisibilityEnum {
    return value as VisibilityEnum;
}

