# Generated by Django 6.0.4 on 2026-06-01 21:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codepeat', '0001_initial'),
        ('openbook_content', '0006_alter_textbookpage_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='challenge',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='challenges', to='openbook_content.course', verbose_name='Course'),
        ),
    ]
