# Generated by Django 6.0.6 on 2026-06-29 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codepeat', '0006_useravatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='zip_file',
            field=models.FileField(blank=True, null=True, upload_to='submissions/', verbose_name='Submission ZIP'),
        ),
    ]
