# Generated by Django 6.0.6 on 2026-06-29 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codepeat', '0007_alter_submission_zip_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='challenge',
            name='constraints',
            field=models.TextField(blank=True, default='', verbose_name='Constraints'),
        ),
        migrations.AddField(
            model_name='challenge',
            name='example_input',
            field=models.TextField(blank=True, default='', verbose_name='Example Input'),
        ),
        migrations.AddField(
            model_name='challenge',
            name='example_language',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='Example Language'),
        ),
        migrations.AddField(
            model_name='challenge',
            name='example_output',
            field=models.TextField(blank=True, default='', verbose_name='Example Output'),
        ),
        migrations.AddField(
            model_name='challenge',
            name='views',
            field=models.PositiveIntegerField(default=0, verbose_name='Views'),
        ),
    ]
