# Generated by Django 6.0.6 on 2026-06-29 06:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codepeat', '0010_teacher_delete_challenge_permission'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReflectionQuestion',
            fields=[
                ('id', models.UUIDField(editable=False, primary_key=True, serialize=False, verbose_name='Id')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created At')),
                ('modified_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Modified At')),
                ('text', models.TextField(verbose_name='Question')),
                ('kind', models.CharField(choices=[('text', 'Free text'), ('scale', 'Scale'), ('choice', 'Choice')], default='text', max_length=10, verbose_name='Answer type')),
                ('options', models.JSONField(blank=True, default=list, verbose_name='Options')),
                ('position', models.PositiveIntegerField(default=0, verbose_name='Position')),
                ('challenge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reflection_questions', to='codepeat.challenge', verbose_name='Challenge')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Modified By')),
            ],
            options={
                'verbose_name': 'Reflection Question',
                'verbose_name_plural': 'Reflection Questions',
                'ordering': ['position', 'created_at'],
            },
        ),
    ]
