# Generated by Django 6.0.6 on 2026-07-02 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codepeat', '0011_reflectionquestion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedback',
            name='rating',
        ),
        migrations.AddField(
            model_name='challenge',
            name='requires_grading',
            field=models.BooleanField(default=True, verbose_name='Requires grading'),
        ),
        migrations.AddField(
            model_name='submission',
            name='hidden_from_student',
            field=models.BooleanField(default=False, verbose_name='Hidden from student'),
        ),
        migrations.AddField(
            model_name='submission',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], default='pending', max_length=10, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='comments',
            field=models.TextField(blank=True, default='', verbose_name='Comments'),
        ),
    ]
