# Generated by Django 6.0.6 on 2026-07-02 07:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codepeat', '0012_remove_feedback_rating_challenge_requires_grading_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LegalDocument',
            fields=[
                ('id', models.UUIDField(editable=False, primary_key=True, serialize=False, verbose_name='Id')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created At')),
                ('modified_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Modified At')),
                ('slug', models.SlugField(choices=[('datenschutz', 'Privacy policy'), ('impressum', 'Imprint')], max_length=32, unique=True, verbose_name='Slug')),
                ('content', models.TextField(blank=True, default='', verbose_name='Content')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Modified By')),
            ],
            options={
                'verbose_name': 'Legal Document',
                'verbose_name_plural': 'Legal Documents',
                'ordering': ['slug'],
            },
        ),
    ]
