# Generated by Django 6.0.6 on 2026-07-06 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codepeat', '0014_seed_legal_documents'),
    ]

    operations = [
        migrations.AddField(
            model_name='challenge',
            name='categories',
            field=models.JSONField(blank=True, default=list, verbose_name='Categories'),
        ),
    ]
