# Generated by Django 6.0.6 on 2026-07-06 02:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codepeat', '0015_challenge_categories'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChallengeFavorite',
            fields=[
                ('id', models.UUIDField(editable=False, primary_key=True, serialize=False, verbose_name='Id')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created At')),
                ('modified_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Modified At')),
                ('challenge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorites', to='codepeat.challenge', verbose_name='Challenge')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Modified By')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='codepeat_challenge_favorites', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Challenge Favorite',
                'verbose_name_plural': 'Challenge Favorites',
                'constraints': [models.UniqueConstraint(fields=('challenge', 'user'), name='unique_challenge_favorite_per_user')],
            },
        ),
    ]
