/** In-memory fixtures backing the challenge service. Read only via that service. */

import type {Challenge, ChallengeExample} from "./challenges.types.js";

// `solved` is per-user and added by the service from MOCK_USER_PROGRESS.
type CatalogChallenge = Omit<Challenge, "solved">;

// Heavy detail fields served only by the detail endpoint, keyed by challenge id.
interface ChallengeContent {
    views: number;
    tasks: string[];
    constraints: string[];
    example: ChallengeExample;
}

export const MOCK_CHALLENGES: CatalogChallenge[] = [
    {
        id:          "1",
        title:       "Two Sum Variants",
        description: "Finde zwei Indizes, deren Werte eine Zielsumme ergeben.",
        difficulty:  "easy",
        status:      "open",
        favorited:   false,
        categories:  ["Arrays", "Algorithmen und Datenstrukturen", "CodePeat", "Math"],
        popular:     true,
        isNew:       false,
        assigned:    false,
        createdAt:   "2025-01-15",
        solvedCount: 1240,
        createdBy:   "u2",
    },
    {
        id:          "2",
        title:       "Valid Brackets",
        description: "Prüfe, ob eine Zeichenkette korrekt geschachtelte Klammern enthält.",
        difficulty:  "easy",
        status:      "open",
        favorited:   false,
        categories:  ["Stacks", "CodePeat"],
        popular:     true,
        isNew:       false,
        assigned:    false,
        createdAt:   "2025-02-03",
        solvedCount: 980,
        createdBy:   "u2",
    },
    {
        id:          "3",
        title:       "Merge Sorted Arrays",
        description: "Führe zwei sortierte Arrays zu einem sortierten Array zusammen.",
        difficulty:  "medium",
        status:      "locked",
        favorited:   false,
        categories:  ["Arrays", "Algorithmen und Datenstrukturen", "Sorting"],
        popular:     false,
        isNew:       false,
        assigned:    true,
        createdAt:   "2025-03-10",
        solvedCount: 420,
        createdBy:   "u2",
    },
    {
        id:          "4",
        title:       "WebProg Challenge erste Vorlesung",
        description: "Die Erste Challenge aus der ersten Vorlesung, welche ich nur für freigeschaltete Nutzer sichtbar geschaltet habe und selbst erstellt habe.",
        difficulty:  "easy",
        status:      "open",
        favorited:   false,
        categories:  ["Eigene"],
        popular:     false,
        isNew:       true,
        assigned:    false,
        createdAt:   "2026-05-20",
        solvedCount: 3,
        createdBy:   "u1",
    },
    {
        id:          "5",
        title:       "Reverse Linked List",
        description: "Kehre eine einfach verkettete Liste um.",
        difficulty:  "medium",
        status:      "locked",
        favorited:   false,
        categories:  ["Linked Lists", "Algorithmen und Datenstrukturen"],
        popular:     false,
        isNew:       false,
        assigned:    true,
        createdAt:   "2025-02-28",
        solvedCount: 610,
        createdBy:   "u2",
    },
    {
        id:          "6",
        title:       "Binary Tree Level Order Traversal",
        description: "Gib die Knoten eines Binärbaums levelweise aus.",
        difficulty:  "medium",
        status:      "locked",
        favorited:   false,
        categories:  ["Trees", "Algorithmen und Datenstrukturen"],
        popular:     false,
        isNew:       false,
        assigned:    false,
        createdAt:   "2025-04-05",
        solvedCount: 290,
        createdBy:   "u2",
    },
    {
        id:          "7",
        title:       "Max Subarray Sum",
        description: "Ermittle die maximale Summe eines zusammenhängenden Teilarrays.",
        difficulty:  "hard",
        status:      "locked",
        favorited:   false,
        categories:  ["Arrays", "Fortgeschritten", "Dynamic Programming"],
        popular:     true,
        isNew:       false,
        assigned:    false,
        createdAt:   "2025-01-30",
        solvedCount: 530,
        createdBy:   "u2",
    },
    {
        id:          "8",
        title:       "Detect Cycle in Linked List",
        description: "Addiere Zwei Zahlen",
        difficulty:  "easy",
        status:      "locked",
        favorited:   false,
        categories:  ["Linked Lists"],
        popular:     false,
        isNew:       true,
        assigned:    false,
        createdAt:   "2026-05-25",
        solvedCount: 45,
        createdBy:   "u2",
    },
    {
        id:          "9",
        title:       "Climbing Stairs",
        description: "Zähle, auf wie viele Arten man eine Treppe mit 1er- oder 2er-Schritten erreichen kann.",
        difficulty:  "easy",
        status:      "open",
        favorited:   false,
        categories:  ["Dynamic Programming", "Math"],
        popular:     true,
        isNew:       false,
        assigned:    false,
        createdAt:   "2025-03-22",
        solvedCount: 870,
        createdBy:   "u2",
    },
    {
        id:          "10",
        title:       "Fibonacci Number",
        description: "Berechne die n-te Fibonacci-Zahl effizient.",
        difficulty:  "easy",
        status:      "locked",
        favorited:   false,
        categories:  ["Dynamic Programming", "Math"],
        popular:     false,
        isNew:       false,
        assigned:    false,
        createdAt:   "2025-04-18",
        solvedCount: 760,
        createdBy:   "u2",
    },
    {
        id:          "11",
        title:       "Quick Sort Implementation",
        description: "Implementiere Quicksort und sortiere ein Array aufsteigend.",
        difficulty:  "medium",
        status:      "locked",
        favorited:   false,
        categories:  ["Sorting", "Algorithmen und Datenstrukturen"],
        popular:     false,
        isNew:       true,
        assigned:    false,
        createdAt:   "2025-05-02",
        solvedCount: 410,
        createdBy:   "u2",
    },
    {
        id:          "12",
        title:       "Binary Search",
        description: "Finde den Index eines Zielwerts in einem sortierten Array.",
        difficulty:  "easy",
        status:      "open",
        favorited:   false,
        categories:  ["Arrays", "Algorithmen und Datenstrukturen", "CodePeat"],
        popular:     true,
        isNew:       false,
        assigned:    false,
        createdAt:   "2025-01-20",
        solvedCount: 1530,
        createdBy:   "u2",
    },
    {
        id:          "13",
        title:       "Contains Duplicate",
        description: "Prüfe, ob ein Array doppelte Werte enthält.",
        difficulty:  "easy",
        status:      "open",
        favorited:   false,
        categories:  ["Arrays", "CodePeat"],
        popular:     false,
        isNew:       false,
        assigned:    false,
        createdAt:   "2025-02-11",
        solvedCount: 1120,
        createdBy:   "u2",
    },
    {
        id:          "14",
        title:       "Best Time to Buy and Sell Stock",
        description: "Finde den maximalen Gewinn aus einem einzigen Kauf und Verkauf.",
        difficulty:  "easy",
        status:      "open",
        favorited:   false,
        categories:  ["Arrays", "Dynamic Programming"],
        popular:     true,
        isNew:       false,
        assigned:    false,
        createdAt:   "2025-02-18",
        solvedCount: 990,
        createdBy:   "u2",
    },
    {
        id:          "15",
        title:       "Product of Array Except Self",
        description: "Berechne für jeden Index das Produkt aller anderen Elemente.",
        difficulty:  "medium",
        status:      "locked",
        favorited:   false,
        categories:  ["Arrays", "Algorithmen und Datenstrukturen"],
        popular:     false,
        isNew:       false,
        assigned:    false,
        createdAt:   "2025-03-01",
        solvedCount: 540,
        createdBy:   "u1",
    },
    {
        id:          "16",
        title:       "Min Stack",
        description: "Implementiere einen Stack mit konstantem getMin().",
        difficulty:  "medium",
        status:      "locked",
        favorited:   false,
        categories:  ["Stacks", "Algorithmen und Datenstrukturen"],
        popular:     false,
        isNew:       true,
        assigned:    false,
        createdAt:   "2026-05-12",
        solvedCount: 60,
        createdBy:   "u1",
    },
    {
        id:          "17",
        title:       "Evaluate Reverse Polish Notation",
        description: "Werte einen Ausdruck in umgekehrter polnischer Notation aus.",
        difficulty:  "medium",
        status:      "open",
        favorited:   false,
        categories:  ["Stacks", "Math"],
        popular:     false,
        isNew:       false,
        assigned:    false,
        createdAt:   "2025-03-15",
        solvedCount: 410,
        createdBy:   "u2",
    },
    {
        id:          "18",
        title:       "Daily Temperatures",
        description: "Bestimme für jeden Tag, wie viele Tage bis zu einer wärmeren Temperatur vergehen.",
        difficulty:  "medium",
        status:      "locked",
        favorited:   false,
        categories:  ["Stacks", "Arrays"],
        popular:     false,
        isNew:       false,
        assigned:    false,
        createdAt:   "2025-03-28",
        solvedCount: 360,
        createdBy:   "u2",
    },
    {
        id:          "19",
        title:       "Number of Islands",
        description: "Zähle die zusammenhängenden Landflächen in einem Gitter.",
        difficulty:  "medium",
        status:      "locked",
        favorited:   false,
        categories:  ["Algorithmen und Datenstrukturen", "Fortgeschritten"],
        popular:     true,
        isNew:       false,
        assigned:    false,
        createdAt:   "2025-04-02",
        solvedCount: 480,
        createdBy:   "u2",
    },
    {
        id:          "20",
        title:       "Course Schedule",
        description: "Prüfe, ob alle Kurse bei gegebenen Abhängigkeiten abgeschlossen werden können.",
        difficulty:  "hard",
        status:      "locked",
        favorited:   false,
        categories:  ["Algorithmen und Datenstrukturen", "Fortgeschritten"],
        popular:     false,
        isNew:       false,
        assigned:    false,
        createdAt:   "2025-04-10",
        solvedCount: 220,
        createdBy:   "u2",
    },
    {
        id:          "21",
        title:       "Lowest Common Ancestor",
        description: "Finde den niedrigsten gemeinsamen Vorfahren zweier Knoten in einem Baum.",
        difficulty:  "medium",
        status:      "locked",
        favorited:   false,
        categories:  ["Trees", "Algorithmen und Datenstrukturen"],
        popular:     false,
        isNew:       false,
        assigned:    false,
        createdAt:   "2025-04-22",
        solvedCount: 300,
        createdBy:   "u2",
    },
    {
        id:          "22",
        title:       "Validate Binary Search Tree",
        description: "Prüfe, ob ein Binärbaum ein gültiger Suchbaum ist.",
        difficulty:  "medium",
        status:      "locked",
        favorited:   false,
        categories:  ["Trees", "Algorithmen und Datenstrukturen"],
        popular:     false,
        isNew:       false,
        assigned:    false,
        createdAt:   "2025-05-05",
        solvedCount: 350,
        createdBy:   "u2",
    },
    {
        id:          "23",
        title:       "Kth Largest Element",
        description: "Finde das k-größte Element in einem unsortierten Array.",
        difficulty:  "medium",
        status:      "open",
        favorited:   false,
        categories:  ["Sorting", "Arrays"],
        popular:     false,
        isNew:       false,
        assigned:    false,
        createdAt:   "2025-05-12",
        solvedCount: 420,
        createdBy:   "u2",
    },
    {
        id:          "24",
        title:       "Merge Intervals",
        description: "Führe überlappende Intervalle zu einem zusammen.",
        difficulty:  "medium",
        status:      "locked",
        favorited:   false,
        categories:  ["Sorting", "Arrays"],
        popular:     false,
        isNew:       true,
        assigned:    false,
        createdAt:   "2026-05-18",
        solvedCount: 75,
        createdBy:   "u1",
    },
    {
        id:          "25",
        title:       "Insert Interval",
        description: "Füge ein neues Intervall in eine sortierte, nicht überlappende Liste ein.",
        difficulty:  "medium",
        status:      "open",
        favorited:   false,
        categories:  ["Arrays", "Sorting"],
        popular:     false,
        isNew:       false,
        assigned:    false,
        createdAt:   "2025-05-20",
        solvedCount: 280,
        createdBy:   "u2",
    },
    {
        id:          "26",
        title:       "Coin Change",
        description: "Bestimme die minimale Anzahl Münzen für einen Betrag.",
        difficulty:  "hard",
        status:      "locked",
        favorited:   false,
        categories:  ["Dynamic Programming", "Fortgeschritten"],
        popular:     true,
        isNew:       false,
        assigned:    false,
        createdAt:   "2025-05-25",
        solvedCount: 510,
        createdBy:   "u2",
    },
    {
        id:          "27",
        title:       "Longest Common Subsequence",
        description: "Finde die Länge der längsten gemeinsamen Teilsequenz zweier Strings.",
        difficulty:  "medium",
        status:      "locked",
        favorited:   false,
        categories:  ["Dynamic Programming"],
        popular:     false,
        isNew:       false,
        assigned:    false,
        createdAt:   "2025-06-01",
        solvedCount: 340,
        createdBy:   "u2",
    },
    {
        id:          "28",
        title:       "House Robber",
        description: "Maximiere die Beute, ohne zwei benachbarte Häuser zu bestehlen.",
        difficulty:  "medium",
        status:      "open",
        favorited:   false,
        categories:  ["Dynamic Programming"],
        popular:     false,
        isNew:       false,
        assigned:    false,
        createdAt:   "2025-06-03",
        solvedCount: 460,
        createdBy:   "u1",
    },
    {
        id:          "29",
        title:       "Word Search",
        description: "Prüfe, ob ein Wort in einem Buchstabengitter existiert.",
        difficulty:  "hard",
        status:      "locked",
        favorited:   false,
        categories:  ["Algorithmen und Datenstrukturen", "Fortgeschritten"],
        popular:     false,
        isNew:       true,
        assigned:    false,
        createdAt:   "2026-05-28",
        solvedCount: 130,
        createdBy:   "u2",
    },
    {
        id:          "30",
        title:       "Palindrome Number",
        description: "Prüfe, ob eine ganze Zahl ein Palindrom ist.",
        difficulty:  "easy",
        status:      "open",
        favorited:   false,
        categories:  ["Math"],
        popular:     false,
        isNew:       false,
        assigned:    false,
        createdAt:   "2025-06-05",
        solvedCount: 880,
        createdBy:   "u2",
    },
];

/**
 * Which challenge ids each user has solved. The service uses this to set the
 * per-user `solved` flag for the logged-in user (mirrors a backend that returns
 * the requesting user's progress).
 */
export const MOCK_USER_PROGRESS: Record<string, string[]> = {
    u1: ["1", "2", "9"], // Diana
    u2: ["3", "4", "5"],
};

export const MOCK_CHALLENGE_DETAILS: Record<string, ChallengeContent> = {
    "1": {
        views: 2480,
        tasks: [
            "Schreibe eine Funktion, die zwei Indizes zurückgibt, deren Werte zusammen die Zielsumme ergeben.",
            "Jedes Element darf nur einmal verwendet werden.",
        ],
        constraints: ["Es gibt genau eine gültige Lösung.", "Die Reihenfolge der Indizes spielt keine Rolle."],
        example: {language: "Java", input: "nums = [2,7,11,15], target = 9", output: "[0,1]"},
    },
    "2": {
        views: 1960,
        tasks: [
            "Prüfe, ob eine Zeichenkette aus Klammern korrekt geschachtelt ist.",
            "Erlaubt sind die Zeichen (), [] und {}.",
        ],
        constraints: ["Die Eingabe enthält ausschließlich Klammerzeichen.", "Eine leere Zeichenkette gilt als gültig."],
        example: {language: "Java", input: "s = \"([]{})\"", output: "true"},
    },
    "3": {
        views: 165,
        tasks: [
            "Schreibe eine Funktion, die alle Elemente aus nums2 in das Array nums1 einfügt.",
            "nums1 enthält am Anfang genau so viele leere Plätze, wie nums2 Elemente hat, und soll nach dem Einfügen vollständig sortiert sein.",
        ],
        constraints: ["Beide Arrays sind sortiert", "Du darfst keine Sortierfunktion benutzen"],
        example: {language: "Java", input: "nums1 = [1,2,3,0,0,0]", output: "nums2 = [4,5,6]"},
    },
    "4": {
        views: 18,
        tasks: [
            "Implementiere die Aufgabe aus der ersten Vorlesung.",
            "Halte dich an die in der Vorlesung besprochene Funktionssignatur.",
        ],
        constraints: ["Nur für freigeschaltete Nutzer sichtbar.", "Keine externen Bibliotheken verwenden."],
        example: {language: "Java", input: "eingabe = \"hallo welt\"", output: "\"HALLO WELT\""},
    },
    "5": {
        views: 1220,
        tasks: ["Kehre eine einfach verkettete Liste um und gib den neuen Kopf zurück."],
        constraints: ["Die Liste kann leer sein.", "Löse die Aufgabe iterativ in O(n)."],
        example: {language: "Java", input: "head = [1,2,3,4,5]", output: "[5,4,3,2,1]"},
    },
    "6": {
        views: 580,
        tasks: ["Gib die Knoten eines Binärbaums Ebene für Ebene als Liste von Listen aus."],
        constraints: ["Die Anzahl der Knoten liegt zwischen 0 und 2000."],
        example: {language: "Java", input: "root = [3,9,20,null,null,15,7]", output: "[[3],[9,20],[15,7]]"},
    },
    "7": {
        views: 1060,
        tasks: ["Finde die maximale Summe eines zusammenhängenden Teilarrays."],
        constraints: ["Das Array enthält mindestens ein Element.", "Erwartete Laufzeit: O(n)."],
        example: {language: "Java", input: "nums = [-2,1,-3,4,-1,2,1,-5,4]", output: "6"},
    },
    "8": {
        views: 90,
        tasks: ["Prüfe, ob eine einfach verkettete Liste einen Zyklus enthält."],
        constraints: ["Löse die Aufgabe mit konstantem Speicherverbrauch."],
        example: {language: "Java", input: "head = [3,2,0,-4], pos = 1", output: "true"},
    },
    "9": {
        views: 1740,
        tasks: [
            "Berechne, auf wie viele Arten man eine Treppe mit n Stufen erreichen kann.",
            "Pro Schritt sind 1 oder 2 Stufen erlaubt.",
        ],
        constraints: ["1 <= n <= 45."],
        example: {language: "Java", input: "n = 4", output: "5"},
    },
    "10": {
        views: 1520,
        tasks: ["Berechne die n-te Fibonacci-Zahl effizient."],
        constraints: ["0 <= n <= 30.", "Es gilt F(0) = 0 und F(1) = 1."],
        example: {language: "Java", input: "n = 6", output: "8"},
    },
    "11": {
        views: 820,
        tasks: ["Implementiere Quicksort und sortiere ein Array aufsteigend."],
        constraints: ["Sortiere in-place.", "Erwartete Laufzeit: O(n log n)."],
        example: {language: "Java", input: "arr = [5,2,9,1,5,6]", output: "[1,2,5,5,6,9]"},
    },
    "12": {
        views: 3060,
        tasks: ["Implementiere die binäre Suche und gib den Index des Zielwerts zurück, sonst -1."],
        constraints: ["Das Array ist aufsteigend sortiert.", "Erwartete Laufzeit: O(log n)."],
        example: {language: "Java", input: "nums = [-1,0,3,5,9,12], target = 9", output: "4"},
    },
    "13": {
        views: 2240,
        tasks: ["Gib true zurück, wenn ein Wert mindestens zweimal im Array vorkommt."],
        constraints: ["1 <= nums.length <= 100000."],
        example: {language: "Java", input: "nums = [1,2,3,1]", output: "true"},
    },
    "14": {
        views: 1980,
        tasks: ["Finde den maximal möglichen Gewinn aus genau einem Kauf und einem späteren Verkauf."],
        constraints: ["Du darfst nur einmal kaufen und verkaufen.", "Gibt es keinen Gewinn, ist das Ergebnis 0."],
        example: {language: "Java", input: "prices = [7,1,5,3,6,4]", output: "5"},
    },
    "15": {
        views: 1080,
        tasks: [
            "Gib ein Array zurück, in dem jeder Eintrag das Produkt aller anderen Elemente ist.",
            "Löse die Aufgabe ohne Division.",
        ],
        constraints: ["Erwartete Laufzeit: O(n)."],
        example: {language: "Java", input: "nums = [1,2,3,4]", output: "[24,12,8,6]"},
    },
    "16": {
        views: 60,
        tasks: ["Implementiere push, pop, top und getMin jeweils in O(1)."],
        constraints: ["getMin muss in konstanter Zeit laufen."],
        example: {language: "Java", input: "push(-2); push(0); push(-3); getMin()", output: "-3"},
    },
    "17": {
        views: 820,
        tasks: ["Werte einen arithmetischen Ausdruck in umgekehrter polnischer Notation aus."],
        constraints: ["Gültige Operatoren sind +, -, * und /."],
        example: {language: "Java", input: "tokens = [\"2\",\"1\",\"+\",\"3\",\"*\"]", output: "9"},
    },
    "18": {
        views: 720,
        tasks: ["Gib für jeden Tag die Anzahl der Tage bis zu einer wärmeren Temperatur zurück."],
        constraints: ["Erwartete Laufzeit: O(n)."],
        example: {language: "Java", input: "temperatures = [73,74,75,71,69,72,76,73]", output: "[1,1,4,2,1,1,0,0]"},
    },
    "19": {
        views: 960,
        tasks: ["Zähle die zusammenhängenden Inseln (Felder mit '1') im Gitter."],
        constraints: ["Felder sind '0' (Wasser) oder '1' (Land).", "Benachbarungen nur horizontal und vertikal."],
        example: {language: "Java", input: "grid = [[\"1\",\"1\",\"0\"],[\"0\",\"1\",\"0\"],[\"0\",\"0\",\"1\"]]", output: "2"},
    },
    "20": {
        views: 440,
        tasks: ["Prüfe, ob alle Kurse trotz ihrer Abhängigkeiten abgeschlossen werden können."],
        constraints: ["Es kann zyklische Abhängigkeiten geben."],
        example: {language: "Java", input: "numCourses = 2, prerequisites = [[1,0]]", output: "true"},
    },
    "21": {
        views: 600,
        tasks: ["Finde den niedrigsten gemeinsamen Vorfahren der Knoten p und q."],
        constraints: ["Alle Knotenwerte sind eindeutig."],
        example: {language: "Java", input: "root = [6,2,8,0,4,7,9], p = 2, q = 8", output: "6"},
    },
    "22": {
        views: 700,
        tasks: ["Prüfe, ob der Baum ein gültiger binärer Suchbaum ist."],
        constraints: ["Linke Teilbäume < Knoten < rechte Teilbäume."],
        example: {language: "Java", input: "root = [2,1,3]", output: "true"},
    },
    "23": {
        views: 840,
        tasks: ["Finde das k-größte Element im unsortierten Array."],
        constraints: ["1 <= k <= nums.length."],
        example: {language: "Java", input: "nums = [3,2,1,5,6,4], k = 2", output: "5"},
    },
    "24": {
        views: 75,
        tasks: ["Führe alle überlappenden Intervalle zu jeweils einem zusammen."],
        constraints: ["Die Intervalle können unsortiert sein."],
        example: {language: "Java", input: "intervals = [[1,3],[2,6],[8,10]]", output: "[[1,6],[8,10]]"},
    },
    "25": {
        views: 560,
        tasks: ["Füge newInterval ein und vereinige dabei überlappende Intervalle."],
        constraints: ["Die Liste ist sortiert und überlappungsfrei."],
        example: {language: "Java", input: "intervals = [[1,3],[6,9]], newInterval = [2,5]", output: "[[1,5],[6,9]]"},
    },
    "26": {
        views: 1020,
        tasks: ["Bestimme die minimale Anzahl Münzen für den Betrag, sonst -1."],
        constraints: ["1 <= coins.length <= 12."],
        example: {language: "Java", input: "coins = [1,2,5], amount = 11", output: "3"},
    },
    "27": {
        views: 680,
        tasks: ["Finde die Länge der längsten gemeinsamen Teilsequenz zweier Strings."],
        constraints: ["1 <= text.length <= 1000."],
        example: {language: "Java", input: "text1 = \"abcde\", text2 = \"ace\"", output: "3"},
    },
    "28": {
        views: 920,
        tasks: ["Maximiere die Summe, ohne zwei benachbarte Häuser zu bestehlen."],
        constraints: ["0 <= nums.length <= 100."],
        example: {language: "Java", input: "nums = [2,7,9,3,1]", output: "12"},
    },
    "29": {
        views: 260,
        tasks: ["Prüfe, ob das Wort im Gitter über benachbarte Zellen gebildet werden kann."],
        constraints: ["Eine Zelle darf pro Wort nur einmal genutzt werden."],
        example: {language: "Java", input: "board = [[\"A\",\"B\"],[\"C\",\"D\"]], word = \"ABDC\"", output: "true"},
    },
    "30": {
        views: 1760,
        tasks: ["Prüfe ohne Umwandlung in einen String, ob die Zahl ein Palindrom ist."],
        constraints: ["Negative Zahlen sind keine Palindrome."],
        example: {language: "Java", input: "x = 121", output: "true"},
    },
};
