/* tslint:disable */
/* eslint-disable */
/**
 * OpenBook API
 * Beautiful and Engaging Learning Materials
 *
 * The version of the OpenAPI document: 0.0.1-pre1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * * `pending` - Decision Pending
 * * `accepted` - Accepted
 * * `denied` - Denied
 * @export
 */
export const AccessRequestDecisionEnum = {
    Pending: 'pending',
    Accepted: 'accepted',
    Denied: 'denied'
} as const;
export type AccessRequestDecisionEnum = typeof AccessRequestDecisionEnum[keyof typeof AccessRequestDecisionEnum];


export function instanceOfAccessRequestDecisionEnum(value: any): boolean {
    for (const key in AccessRequestDecisionEnum) {
        if (Object.prototype.hasOwnProperty.call(AccessRequestDecisionEnum, key)) {
            if (AccessRequestDecisionEnum[key as keyof typeof AccessRequestDecisionEnum] === value) {
                return true;
            }
        }
    }
    return false;
}

export function AccessRequestDecisionEnumFromJSON(json: any): AccessRequestDecisionEnum {
    return AccessRequestDecisionEnumFromJSONTyped(json, false);
}

export function AccessRequestDecisionEnumFromJSONTyped(json: any, ignoreDiscriminator: boolean): AccessRequestDecisionEnum {
    return json as AccessRequestDecisionEnum;
}

export function AccessRequestDecisionEnumToJSON(value?: AccessRequestDecisionEnum | null): any {
    return value as any;
}

export function AccessRequestDecisionEnumToJSONTyped(value: any, ignoreDiscriminator: boolean): AccessRequestDecisionEnum {
    return value as AccessRequestDecisionEnum;
}

