/* tslint:disable */
/* eslint-disable */
/**
 * OpenBook API
 * Beautiful and Engaging Learning Materials
 *
 * The version of the OpenAPI document: 0.0.1-pre1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AccountActionResult
 */
export interface AccountActionResult {
    /**
     * 
     * @type {string}
     * @memberof AccountActionResult
     */
    detail: string;
}

/**
 * Check if a given object implements the AccountActionResult interface.
 */
export function instanceOfAccountActionResult(value: object): value is AccountActionResult {
    if (!('detail' in value) || value['detail'] === undefined) return false;
    return true;
}

export function AccountActionResultFromJSON(json: any): AccountActionResult {
    return AccountActionResultFromJSONTyped(json, false);
}

export function AccountActionResultFromJSONTyped(json: any, ignoreDiscriminator: boolean): AccountActionResult {
    if (json == null) {
        return json;
    }
    return {
        
        'detail': json['detail'],
    };
}

export function AccountActionResultToJSON(json: any): AccountActionResult {
    return AccountActionResultToJSONTyped(json, false);
}

export function AccountActionResultToJSONTyped(value?: AccountActionResult | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'detail': value['detail'],
    };
}

