/* tslint:disable */
/* eslint-disable */
/**
 * OpenBook API
 * Beautiful and Engaging Learning Materials
 *
 * The version of the OpenAPI document: 0.0.1-pre1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ChallengeUnlock
 */
export interface ChallengeUnlock {
    /**
     * 
     * @type {string}
     * @memberof ChallengeUnlock
     */
    token: string;
}

/**
 * Check if a given object implements the ChallengeUnlock interface.
 */
export function instanceOfChallengeUnlock(value: object): value is ChallengeUnlock {
    if (!('token' in value) || value['token'] === undefined) return false;
    return true;
}

export function ChallengeUnlockFromJSON(json: any): ChallengeUnlock {
    return ChallengeUnlockFromJSONTyped(json, false);
}

export function ChallengeUnlockFromJSONTyped(json: any, ignoreDiscriminator: boolean): ChallengeUnlock {
    if (json == null) {
        return json;
    }
    return {
        
        'token': json['token'],
    };
}

export function ChallengeUnlockToJSON(json: any): ChallengeUnlock {
    return ChallengeUnlockToJSONTyped(json, false);
}

export function ChallengeUnlockToJSONTyped(value?: ChallengeUnlock | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'token': value['token'],
    };
}

