/* tslint:disable */
/* eslint-disable */
/**
 * OpenBook API
 * Beautiful and Engaging Learning Materials
 *
 * The version of the OpenAPI document: 0.0.1-pre1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { VisibilityEnum } from './VisibilityEnum';
import {
    VisibilityEnumFromJSON,
    VisibilityEnumFromJSONTyped,
    VisibilityEnumToJSON,
    VisibilityEnumToJSONTyped,
} from './VisibilityEnum';
import type { TextFormatEnum } from './TextFormatEnum';
import {
    TextFormatEnumFromJSON,
    TextFormatEnumFromJSONTyped,
    TextFormatEnumToJSON,
    TextFormatEnumToJSONTyped,
} from './TextFormatEnum';
import type { DifficultyEnum } from './DifficultyEnum';
import {
    DifficultyEnumFromJSON,
    DifficultyEnumFromJSONTyped,
    DifficultyEnumToJSON,
    DifficultyEnumToJSONTyped,
} from './DifficultyEnum';
import type { TypeEnum } from './TypeEnum';
import {
    TypeEnumFromJSON,
    TypeEnumFromJSONTyped,
    TypeEnumToJSON,
    TypeEnumToJSONTyped,
} from './TypeEnum';

/**
 * Reuse full cleaning and validation logic of the models in the REST API.
 * 
 * Reuse ``full_clean()``, ``clean()``, field validation, and uniqueness checks.
 * Also make sure that the pre-filled model instance can be accessed in the DRF view.
 * @export
 * @interface Challenge
 */
export interface Challenge {
    /**
     * 
     * @type {string}
     * @memberof Challenge
     */
    readonly id: string;
    /**
     * 
     * @type {string}
     * @memberof Challenge
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof Challenge
     */
    description?: string;
    /**
     * 
     * @type {TextFormatEnum}
     * @memberof Challenge
     */
    textFormat?: TextFormatEnum;
    /**
     * 
     * @type {DifficultyEnum}
     * @memberof Challenge
     */
    difficulty?: DifficultyEnum;
    /**
     * 
     * @type {VisibilityEnum}
     * @memberof Challenge
     */
    visibility?: VisibilityEnum;
    /**
     * 
     * @type {TypeEnum}
     * @memberof Challenge
     */
    type?: TypeEnum;
    /**
     * 
     * @type {string}
     * @memberof Challenge
     */
    course?: string | null;
    /**
     * 
     * @type {number}
     * @memberof Challenge
     */
    readonly createdBy: number | null;
    /**
     * 
     * @type {Date}
     * @memberof Challenge
     */
    readonly createdAt: Date | null;
    /**
     * 
     * @type {Date}
     * @memberof Challenge
     */
    readonly modifiedAt: Date | null;
}



/**
 * Check if a given object implements the Challenge interface.
 */
export function instanceOfChallenge(value: object): value is Challenge {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('createdBy' in value) || value['createdBy'] === undefined) return false;
    if (!('createdAt' in value) || value['createdAt'] === undefined) return false;
    if (!('modifiedAt' in value) || value['modifiedAt'] === undefined) return false;
    return true;
}

export function ChallengeFromJSON(json: any): Challenge {
    return ChallengeFromJSONTyped(json, false);
}

export function ChallengeFromJSONTyped(json: any, ignoreDiscriminator: boolean): Challenge {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'name': json['name'],
        'description': json['description'] == null ? undefined : json['description'],
        'textFormat': json['text_format'] == null ? undefined : TextFormatEnumFromJSON(json['text_format']),
        'difficulty': json['difficulty'] == null ? undefined : DifficultyEnumFromJSON(json['difficulty']),
        'visibility': json['visibility'] == null ? undefined : VisibilityEnumFromJSON(json['visibility']),
        'type': json['type'] == null ? undefined : TypeEnumFromJSON(json['type']),
        'course': json['course'] == null ? undefined : json['course'],
        'createdBy': json['created_by'],
        'createdAt': (json['created_at'] == null ? null : new Date(json['created_at'])),
        'modifiedAt': (json['modified_at'] == null ? null : new Date(json['modified_at'])),
    };
}

export function ChallengeToJSON(json: any): Challenge {
    return ChallengeToJSONTyped(json, false);
}

export function ChallengeToJSONTyped(value?: Omit<Challenge, 'id'|'created_by'|'created_at'|'modified_at'> | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
        'description': value['description'],
        'text_format': TextFormatEnumToJSON(value['textFormat']),
        'difficulty': DifficultyEnumToJSON(value['difficulty']),
        'visibility': VisibilityEnumToJSON(value['visibility']),
        'type': TypeEnumToJSON(value['type']),
        'course': value['course'],
    };
}

