/* tslint:disable */
/* eslint-disable */
/**
 * OpenBook API
 * Beautiful and Engaging Learning Materials
 *
 * The version of the OpenAPI document: 0.0.1-pre1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ChallengeUnlockResult
 */
export interface ChallengeUnlockResult {
    /**
     * 
     * @type {string}
     * @memberof ChallengeUnlockResult
     */
    challenge: string;
    /**
     * 
     * @type {string}
     * @memberof ChallengeUnlockResult
     */
    detail: string;
}

/**
 * Check if a given object implements the ChallengeUnlockResult interface.
 */
export function instanceOfChallengeUnlockResult(value: object): value is ChallengeUnlockResult {
    if (!('challenge' in value) || value['challenge'] === undefined) return false;
    if (!('detail' in value) || value['detail'] === undefined) return false;
    return true;
}

export function ChallengeUnlockResultFromJSON(json: any): ChallengeUnlockResult {
    return ChallengeUnlockResultFromJSONTyped(json, false);
}

export function ChallengeUnlockResultFromJSONTyped(json: any, ignoreDiscriminator: boolean): ChallengeUnlockResult {
    if (json == null) {
        return json;
    }
    return {
        
        'challenge': json['challenge'],
        'detail': json['detail'],
    };
}

export function ChallengeUnlockResultToJSON(json: any): ChallengeUnlockResult {
    return ChallengeUnlockResultToJSONTyped(json, false);
}

export function ChallengeUnlockResultToJSONTyped(value?: ChallengeUnlockResult | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'challenge': value['challenge'],
        'detail': value['detail'],
    };
}

