/* tslint:disable */
/* eslint-disable */
/**
 * OpenBook API
 * Beautiful and Engaging Learning Materials
 *
 * The version of the OpenAPI document: 0.0.1-pre1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * * `text` - Free text
 * * `scale` - Scale
 * * `choice` - Choice
 * @export
 */
export const KindEnum = {
    Text: 'text',
    Scale: 'scale',
    Choice: 'choice'
} as const;
export type KindEnum = typeof KindEnum[keyof typeof KindEnum];


export function instanceOfKindEnum(value: any): boolean {
    for (const key in KindEnum) {
        if (Object.prototype.hasOwnProperty.call(KindEnum, key)) {
            if (KindEnum[key as keyof typeof KindEnum] === value) {
                return true;
            }
        }
    }
    return false;
}

export function KindEnumFromJSON(json: any): KindEnum {
    return KindEnumFromJSONTyped(json, false);
}

export function KindEnumFromJSONTyped(json: any, ignoreDiscriminator: boolean): KindEnum {
    return json as KindEnum;
}

export function KindEnumToJSON(value?: KindEnum | null): any {
    return value as any;
}

export function KindEnumToJSONTyped(value: any, ignoreDiscriminator: boolean): KindEnum {
    return value as KindEnum;
}

