/* tslint:disable */
/* eslint-disable */
/**
 * OpenBook API
 * Beautiful and Engaging Learning Materials
 *
 * The version of the OpenAPI document: 0.0.1-pre1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Reflection } from './Reflection';
import {
    ReflectionFromJSON,
    ReflectionFromJSONTyped,
    ReflectionToJSON,
    ReflectionToJSONTyped,
} from './Reflection';

/**
 * 
 * @export
 * @interface PaginatedReflectionList
 */
export interface PaginatedReflectionList {
    /**
     * 
     * @type {number}
     * @memberof PaginatedReflectionList
     */
    count: number;
    /**
     * 
     * @type {string}
     * @memberof PaginatedReflectionList
     */
    next?: string | null;
    /**
     * 
     * @type {string}
     * @memberof PaginatedReflectionList
     */
    previous?: string | null;
    /**
     * 
     * @type {Array<Reflection>}
     * @memberof PaginatedReflectionList
     */
    results: Array<Reflection>;
}

/**
 * Check if a given object implements the PaginatedReflectionList interface.
 */
export function instanceOfPaginatedReflectionList(value: object): value is PaginatedReflectionList {
    if (!('count' in value) || value['count'] === undefined) return false;
    if (!('results' in value) || value['results'] === undefined) return false;
    return true;
}

export function PaginatedReflectionListFromJSON(json: any): PaginatedReflectionList {
    return PaginatedReflectionListFromJSONTyped(json, false);
}

export function PaginatedReflectionListFromJSONTyped(json: any, ignoreDiscriminator: boolean): PaginatedReflectionList {
    if (json == null) {
        return json;
    }
    return {
        
        'count': json['count'],
        'next': json['next'] == null ? undefined : json['next'],
        'previous': json['previous'] == null ? undefined : json['previous'],
        'results': ((json['results'] as Array<any>).map(ReflectionFromJSON)),
    };
}

export function PaginatedReflectionListToJSON(json: any): PaginatedReflectionList {
    return PaginatedReflectionListToJSONTyped(json, false);
}

export function PaginatedReflectionListToJSONTyped(value?: PaginatedReflectionList | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'count': value['count'],
        'next': value['next'],
        'previous': value['previous'],
        'results': ((value['results'] as Array<any>).map(ReflectionToJSON)),
    };
}

