/* tslint:disable */
/* eslint-disable */
/**
 * OpenBook API
 * Beautiful and Engaging Learning Materials
 *
 * The version of the OpenAPI document: 0.0.1-pre1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { TestResult } from './TestResult';
import {
    TestResultFromJSON,
    TestResultFromJSONTyped,
    TestResultToJSON,
    TestResultToJSONTyped,
} from './TestResult';

/**
 * 
 * @export
 * @interface PaginatedTestResultList
 */
export interface PaginatedTestResultList {
    /**
     * 
     * @type {number}
     * @memberof PaginatedTestResultList
     */
    count: number;
    /**
     * 
     * @type {string}
     * @memberof PaginatedTestResultList
     */
    next?: string | null;
    /**
     * 
     * @type {string}
     * @memberof PaginatedTestResultList
     */
    previous?: string | null;
    /**
     * 
     * @type {Array<TestResult>}
     * @memberof PaginatedTestResultList
     */
    results: Array<TestResult>;
}

/**
 * Check if a given object implements the PaginatedTestResultList interface.
 */
export function instanceOfPaginatedTestResultList(value: object): value is PaginatedTestResultList {
    if (!('count' in value) || value['count'] === undefined) return false;
    if (!('results' in value) || value['results'] === undefined) return false;
    return true;
}

export function PaginatedTestResultListFromJSON(json: any): PaginatedTestResultList {
    return PaginatedTestResultListFromJSONTyped(json, false);
}

export function PaginatedTestResultListFromJSONTyped(json: any, ignoreDiscriminator: boolean): PaginatedTestResultList {
    if (json == null) {
        return json;
    }
    return {
        
        'count': json['count'],
        'next': json['next'] == null ? undefined : json['next'],
        'previous': json['previous'] == null ? undefined : json['previous'],
        'results': ((json['results'] as Array<any>).map(TestResultFromJSON)),
    };
}

export function PaginatedTestResultListToJSON(json: any): PaginatedTestResultList {
    return PaginatedTestResultListToJSONTyped(json, false);
}

export function PaginatedTestResultListToJSONTyped(value?: PaginatedTestResultList | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'count': value['count'],
        'next': value['next'],
        'previous': value['previous'],
        'results': ((value['results'] as Array<any>).map(TestResultToJSON)),
    };
}

