/* tslint:disable */
/* eslint-disable */
/**
 * OpenBook API
 * Beautiful and Engaging Learning Materials
 *
 * The version of the OpenAPI document: 0.0.1-pre1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Challenge } from './Challenge';
import {
    ChallengeFromJSON,
    ChallengeFromJSONTyped,
    ChallengeToJSON,
    ChallengeToJSONTyped,
} from './Challenge';

/**
 * 
 * @export
 * @interface PaginatedChallengeList
 */
export interface PaginatedChallengeList {
    /**
     * 
     * @type {number}
     * @memberof PaginatedChallengeList
     */
    count: number;
    /**
     * 
     * @type {string}
     * @memberof PaginatedChallengeList
     */
    next?: string | null;
    /**
     * 
     * @type {string}
     * @memberof PaginatedChallengeList
     */
    previous?: string | null;
    /**
     * 
     * @type {Array<Challenge>}
     * @memberof PaginatedChallengeList
     */
    results: Array<Challenge>;
}

/**
 * Check if a given object implements the PaginatedChallengeList interface.
 */
export function instanceOfPaginatedChallengeList(value: object): value is PaginatedChallengeList {
    if (!('count' in value) || value['count'] === undefined) return false;
    if (!('results' in value) || value['results'] === undefined) return false;
    return true;
}

export function PaginatedChallengeListFromJSON(json: any): PaginatedChallengeList {
    return PaginatedChallengeListFromJSONTyped(json, false);
}

export function PaginatedChallengeListFromJSONTyped(json: any, ignoreDiscriminator: boolean): PaginatedChallengeList {
    if (json == null) {
        return json;
    }
    return {
        
        'count': json['count'],
        'next': json['next'] == null ? undefined : json['next'],
        'previous': json['previous'] == null ? undefined : json['previous'],
        'results': ((json['results'] as Array<any>).map(ChallengeFromJSON)),
    };
}

export function PaginatedChallengeListToJSON(json: any): PaginatedChallengeList {
    return PaginatedChallengeListToJSONTyped(json, false);
}

export function PaginatedChallengeListToJSONTyped(value?: PaginatedChallengeList | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'count': value['count'],
        'next': value['next'],
        'previous': value['previous'],
        'results': ((value['results'] as Array<any>).map(ChallengeToJSON)),
    };
}

