/* tslint:disable */
/* eslint-disable */
/**
 * OpenBook API
 * Beautiful and Engaging Learning Materials
 *
 * The version of the OpenAPI document: 0.0.1-pre1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { VisibilityEnum } from './VisibilityEnum';
import {
    VisibilityEnumFromJSON,
    VisibilityEnumFromJSONTyped,
    VisibilityEnumToJSON,
    VisibilityEnumToJSONTyped,
} from './VisibilityEnum';
import type { TextFormatEnum } from './TextFormatEnum';
import {
    TextFormatEnumFromJSON,
    TextFormatEnumFromJSONTyped,
    TextFormatEnumToJSON,
    TextFormatEnumToJSONTyped,
} from './TextFormatEnum';
import type { DifficultyEnum } from './DifficultyEnum';
import {
    DifficultyEnumFromJSON,
    DifficultyEnumFromJSONTyped,
    DifficultyEnumToJSON,
    DifficultyEnumToJSONTyped,
} from './DifficultyEnum';
import type { TypeEnum } from './TypeEnum';
import {
    TypeEnumFromJSON,
    TypeEnumFromJSONTyped,
    TypeEnumToJSON,
    TypeEnumToJSONTyped,
} from './TypeEnum';

/**
 * Reuse full cleaning and validation logic of the models in the REST API.
 * 
 * Reuse ``full_clean()``, ``clean()``, field validation, and uniqueness checks.
 * Also make sure that the pre-filled model instance can be accessed in the DRF view.
 * @export
 * @interface PatchedChallenge
 */
export interface PatchedChallenge {
    /**
     * 
     * @type {string}
     * @memberof PatchedChallenge
     */
    readonly id?: string;
    /**
     * 
     * @type {string}
     * @memberof PatchedChallenge
     */
    name?: string;
    /**
     * 
     * @type {string}
     * @memberof PatchedChallenge
     */
    description?: string;
    /**
     * 
     * @type {TextFormatEnum}
     * @memberof PatchedChallenge
     */
    textFormat?: TextFormatEnum;
    /**
     * 
     * @type {DifficultyEnum}
     * @memberof PatchedChallenge
     */
    difficulty?: DifficultyEnum;
    /**
     * 
     * @type {VisibilityEnum}
     * @memberof PatchedChallenge
     */
    visibility?: VisibilityEnum;
    /**
     * 
     * @type {TypeEnum}
     * @memberof PatchedChallenge
     */
    type?: TypeEnum;
    /**
     * 
     * @type {string}
     * @memberof PatchedChallenge
     */
    constraints?: string;
    /**
     * 
     * @type {string}
     * @memberof PatchedChallenge
     */
    exampleLanguage?: string;
    /**
     * 
     * @type {string}
     * @memberof PatchedChallenge
     */
    exampleInput?: string;
    /**
     * 
     * @type {string}
     * @memberof PatchedChallenge
     */
    exampleOutput?: string;
    /**
     * 
     * @type {number}
     * @memberof PatchedChallenge
     */
    readonly views?: number;
    /**
     * 
     * @type {string}
     * @memberof PatchedChallenge
     */
    course?: string | null;
    /**
     * 
     * @type {number}
     * @memberof PatchedChallenge
     */
    readonly createdBy?: number | null;
    /**
     * 
     * @type {Date}
     * @memberof PatchedChallenge
     */
    readonly createdAt?: Date | null;
    /**
     * 
     * @type {Date}
     * @memberof PatchedChallenge
     */
    readonly modifiedAt?: Date | null;
}



/**
 * Check if a given object implements the PatchedChallenge interface.
 */
export function instanceOfPatchedChallenge(value: object): value is PatchedChallenge {
    return true;
}

export function PatchedChallengeFromJSON(json: any): PatchedChallenge {
    return PatchedChallengeFromJSONTyped(json, false);
}

export function PatchedChallengeFromJSONTyped(json: any, ignoreDiscriminator: boolean): PatchedChallenge {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'name': json['name'] == null ? undefined : json['name'],
        'description': json['description'] == null ? undefined : json['description'],
        'textFormat': json['text_format'] == null ? undefined : TextFormatEnumFromJSON(json['text_format']),
        'difficulty': json['difficulty'] == null ? undefined : DifficultyEnumFromJSON(json['difficulty']),
        'visibility': json['visibility'] == null ? undefined : VisibilityEnumFromJSON(json['visibility']),
        'type': json['type'] == null ? undefined : TypeEnumFromJSON(json['type']),
        'constraints': json['constraints'] == null ? undefined : json['constraints'],
        'exampleLanguage': json['example_language'] == null ? undefined : json['example_language'],
        'exampleInput': json['example_input'] == null ? undefined : json['example_input'],
        'exampleOutput': json['example_output'] == null ? undefined : json['example_output'],
        'views': json['views'] == null ? undefined : json['views'],
        'course': json['course'] == null ? undefined : json['course'],
        'createdBy': json['created_by'] == null ? undefined : json['created_by'],
        'createdAt': json['created_at'] == null ? undefined : (new Date(json['created_at'])),
        'modifiedAt': json['modified_at'] == null ? undefined : (new Date(json['modified_at'])),
    };
}

export function PatchedChallengeToJSON(json: any): PatchedChallenge {
    return PatchedChallengeToJSONTyped(json, false);
}

export function PatchedChallengeToJSONTyped(value?: Omit<PatchedChallenge, 'id'|'views'|'created_by'|'created_at'|'modified_at'> | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
        'description': value['description'],
        'text_format': TextFormatEnumToJSON(value['textFormat']),
        'difficulty': DifficultyEnumToJSON(value['difficulty']),
        'visibility': VisibilityEnumToJSON(value['visibility']),
        'type': TypeEnumToJSON(value['type']),
        'constraints': value['constraints'],
        'example_language': value['exampleLanguage'],
        'example_input': value['exampleInput'],
        'example_output': value['exampleOutput'],
        'course': value['course'],
    };
}

