/* tslint:disable */
/* eslint-disable */
/**
 * OpenBook API
 * Beautiful and Engaging Learning Materials
 *
 * The version of the OpenAPI document: 0.0.1-pre1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Reuse full cleaning and validation logic of the models in the REST API.
 * 
 * Reuse ``full_clean()``, ``clean()``, field validation, and uniqueness checks.
 * Also make sure that the pre-filled model instance can be accessed in the DRF view.
 * @export
 * @interface PatchedFeedback
 */
export interface PatchedFeedback {
    /**
     * 
     * @type {string}
     * @memberof PatchedFeedback
     */
    readonly id?: string;
    /**
     * 
     * @type {string}
     * @memberof PatchedFeedback
     */
    submission?: string;
    /**
     * 
     * @type {number}
     * @memberof PatchedFeedback
     */
    lecturer?: number;
    /**
     * 
     * @type {string}
     * @memberof PatchedFeedback
     */
    comments?: string;
    /**
     * 
     * @type {number}
     * @memberof PatchedFeedback
     */
    rating?: number;
    /**
     * 
     * @type {Date}
     * @memberof PatchedFeedback
     */
    readonly createdAt?: Date | null;
    /**
     * 
     * @type {Date}
     * @memberof PatchedFeedback
     */
    readonly modifiedAt?: Date | null;
}

/**
 * Check if a given object implements the PatchedFeedback interface.
 */
export function instanceOfPatchedFeedback(value: object): value is PatchedFeedback {
    return true;
}

export function PatchedFeedbackFromJSON(json: any): PatchedFeedback {
    return PatchedFeedbackFromJSONTyped(json, false);
}

export function PatchedFeedbackFromJSONTyped(json: any, ignoreDiscriminator: boolean): PatchedFeedback {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'submission': json['submission'] == null ? undefined : json['submission'],
        'lecturer': json['lecturer'] == null ? undefined : json['lecturer'],
        'comments': json['comments'] == null ? undefined : json['comments'],
        'rating': json['rating'] == null ? undefined : json['rating'],
        'createdAt': json['created_at'] == null ? undefined : (new Date(json['created_at'])),
        'modifiedAt': json['modified_at'] == null ? undefined : (new Date(json['modified_at'])),
    };
}

export function PatchedFeedbackToJSON(json: any): PatchedFeedback {
    return PatchedFeedbackToJSONTyped(json, false);
}

export function PatchedFeedbackToJSONTyped(value?: Omit<PatchedFeedback, 'id'|'created_at'|'modified_at'> | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'submission': value['submission'],
        'lecturer': value['lecturer'],
        'comments': value['comments'],
        'rating': value['rating'],
    };
}

