/* tslint:disable */
/* eslint-disable */
/**
 * OpenBook API
 * Beautiful and Engaging Learning Materials
 *
 * The version of the OpenAPI document: 0.0.1-pre1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { SlugEnum } from './SlugEnum';
import {
    SlugEnumFromJSON,
    SlugEnumFromJSONTyped,
    SlugEnumToJSON,
    SlugEnumToJSONTyped,
} from './SlugEnum';

/**
 * Reuse full cleaning and validation logic of the models in the REST API.
 * 
 * Reuse ``full_clean()``, ``clean()``, field validation, and uniqueness checks.
 * Also make sure that the pre-filled model instance can be accessed in the DRF view.
 * @export
 * @interface PatchedLegalDocument
 */
export interface PatchedLegalDocument {
    /**
     * 
     * @type {string}
     * @memberof PatchedLegalDocument
     */
    readonly id?: string;
    /**
     * 
     * @type {SlugEnum}
     * @memberof PatchedLegalDocument
     */
    readonly slug?: SlugEnum;
    /**
     * 
     * @type {string}
     * @memberof PatchedLegalDocument
     */
    content?: string;
    /**
     * 
     * @type {boolean}
     * @memberof PatchedLegalDocument
     */
    readonly canEdit?: boolean;
    /**
     * 
     * @type {Date}
     * @memberof PatchedLegalDocument
     */
    readonly createdAt?: Date | null;
    /**
     * 
     * @type {Date}
     * @memberof PatchedLegalDocument
     */
    readonly modifiedAt?: Date | null;
}



/**
 * Check if a given object implements the PatchedLegalDocument interface.
 */
export function instanceOfPatchedLegalDocument(value: object): value is PatchedLegalDocument {
    return true;
}

export function PatchedLegalDocumentFromJSON(json: any): PatchedLegalDocument {
    return PatchedLegalDocumentFromJSONTyped(json, false);
}

export function PatchedLegalDocumentFromJSONTyped(json: any, ignoreDiscriminator: boolean): PatchedLegalDocument {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'slug': json['slug'] == null ? undefined : SlugEnumFromJSON(json['slug']),
        'content': json['content'] == null ? undefined : json['content'],
        'canEdit': json['can_edit'] == null ? undefined : json['can_edit'],
        'createdAt': json['created_at'] == null ? undefined : (new Date(json['created_at'])),
        'modifiedAt': json['modified_at'] == null ? undefined : (new Date(json['modified_at'])),
    };
}

export function PatchedLegalDocumentToJSON(json: any): PatchedLegalDocument {
    return PatchedLegalDocumentToJSONTyped(json, false);
}

export function PatchedLegalDocumentToJSONTyped(value?: Omit<PatchedLegalDocument, 'id'|'slug'|'can_edit'|'created_at'|'modified_at'> | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'content': value['content'],
    };
}

