/* tslint:disable */
/* eslint-disable */
/**
 * OpenBook API
 * Beautiful and Engaging Learning Materials
 *
 * The version of the OpenAPI document: 0.0.1-pre1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * * `datenschutz` - Privacy policy
 * * `impressum` - Imprint
 * @export
 */
export const SlugEnum = {
    Datenschutz: 'datenschutz',
    Impressum: 'impressum'
} as const;
export type SlugEnum = typeof SlugEnum[keyof typeof SlugEnum];


export function instanceOfSlugEnum(value: any): boolean {
    for (const key in SlugEnum) {
        if (Object.prototype.hasOwnProperty.call(SlugEnum, key)) {
            if (SlugEnum[key as keyof typeof SlugEnum] === value) {
                return true;
            }
        }
    }
    return false;
}

export function SlugEnumFromJSON(json: any): SlugEnum {
    return SlugEnumFromJSONTyped(json, false);
}

export function SlugEnumFromJSONTyped(json: any, ignoreDiscriminator: boolean): SlugEnum {
    return json as SlugEnum;
}

export function SlugEnumToJSON(value?: SlugEnum | null): any {
    return value as any;
}

export function SlugEnumToJSONTyped(value: any, ignoreDiscriminator: boolean): SlugEnum {
    return value as SlugEnum;
}

