/* tslint:disable */
/* eslint-disable */
/**
 * OpenBook API
 * Beautiful and Engaging Learning Materials
 *
 * The version of the OpenAPI document: 0.0.1-pre1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Reuse full cleaning and validation logic of the models in the REST API.
 * 
 * Reuse ``full_clean()``, ``clean()``, field validation, and uniqueness checks.
 * Also make sure that the pre-filled model instance can be accessed in the DRF view.
 * @export
 * @interface Submission
 */
export interface Submission {
    /**
     * 
     * @type {string}
     * @memberof Submission
     */
    readonly id: string;
    /**
     * 
     * @type {string}
     * @memberof Submission
     */
    challenge: string;
    /**
     * 
     * @type {number}
     * @memberof Submission
     */
    user: number;
    /**
     * 
     * @type {string}
     * @memberof Submission
     */
    zipFile: string;
    /**
     * 
     * @type {Date}
     * @memberof Submission
     */
    readonly submittedAt: Date;
    /**
     * 
     * @type {Date}
     * @memberof Submission
     */
    readonly createdAt: Date | null;
    /**
     * 
     * @type {Date}
     * @memberof Submission
     */
    readonly modifiedAt: Date | null;
}

/**
 * Check if a given object implements the Submission interface.
 */
export function instanceOfSubmission(value: object): value is Submission {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('challenge' in value) || value['challenge'] === undefined) return false;
    if (!('user' in value) || value['user'] === undefined) return false;
    if (!('zipFile' in value) || value['zipFile'] === undefined) return false;
    if (!('submittedAt' in value) || value['submittedAt'] === undefined) return false;
    if (!('createdAt' in value) || value['createdAt'] === undefined) return false;
    if (!('modifiedAt' in value) || value['modifiedAt'] === undefined) return false;
    return true;
}

export function SubmissionFromJSON(json: any): Submission {
    return SubmissionFromJSONTyped(json, false);
}

export function SubmissionFromJSONTyped(json: any, ignoreDiscriminator: boolean): Submission {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'challenge': json['challenge'],
        'user': json['user'],
        'zipFile': json['zip_file'],
        'submittedAt': (new Date(json['submitted_at'])),
        'createdAt': (json['created_at'] == null ? null : new Date(json['created_at'])),
        'modifiedAt': (json['modified_at'] == null ? null : new Date(json['modified_at'])),
    };
}

export function SubmissionToJSON(json: any): Submission {
    return SubmissionToJSONTyped(json, false);
}

export function SubmissionToJSONTyped(value?: Omit<Submission, 'id'|'submitted_at'|'created_at'|'modified_at'> | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'challenge': value['challenge'],
        'user': value['user'],
        'zip_file': value['zipFile'],
    };
}

