/* tslint:disable */
/* eslint-disable */
/**
 * OpenBook API
 * Beautiful and Engaging Learning Materials
 *
 * The version of the OpenAPI document: 0.0.1-pre1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { SubmissionGradeDecisionEnum } from './SubmissionGradeDecisionEnum';
import {
    SubmissionGradeDecisionEnumFromJSON,
    SubmissionGradeDecisionEnumFromJSONTyped,
    SubmissionGradeDecisionEnumToJSON,
    SubmissionGradeDecisionEnumToJSONTyped,
} from './SubmissionGradeDecisionEnum';

/**
 * 
 * @export
 * @interface SubmissionGrade
 */
export interface SubmissionGrade {
    /**
     * 
     * @type {SubmissionGradeDecisionEnum}
     * @memberof SubmissionGrade
     */
    decision: SubmissionGradeDecisionEnum;
    /**
     * 
     * @type {string}
     * @memberof SubmissionGrade
     */
    comment?: string;
}



/**
 * Check if a given object implements the SubmissionGrade interface.
 */
export function instanceOfSubmissionGrade(value: object): value is SubmissionGrade {
    if (!('decision' in value) || value['decision'] === undefined) return false;
    return true;
}

export function SubmissionGradeFromJSON(json: any): SubmissionGrade {
    return SubmissionGradeFromJSONTyped(json, false);
}

export function SubmissionGradeFromJSONTyped(json: any, ignoreDiscriminator: boolean): SubmissionGrade {
    if (json == null) {
        return json;
    }
    return {
        
        'decision': SubmissionGradeDecisionEnumFromJSON(json['decision']),
        'comment': json['comment'] == null ? undefined : json['comment'],
    };
}

export function SubmissionGradeToJSON(json: any): SubmissionGrade {
    return SubmissionGradeToJSONTyped(json, false);
}

export function SubmissionGradeToJSONTyped(value?: SubmissionGrade | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'decision': SubmissionGradeDecisionEnumToJSON(value['decision']),
        'comment': value['comment'],
    };
}

