/* tslint:disable */
/* eslint-disable */
/**
 * OpenBook API
 * Beautiful and Engaging Learning Materials
 *
 * The version of the OpenAPI document: 0.0.1-pre1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { SubmissionStatusEnum } from './SubmissionStatusEnum';
import {
    SubmissionStatusEnumFromJSON,
    SubmissionStatusEnumFromJSONTyped,
    SubmissionStatusEnumToJSON,
    SubmissionStatusEnumToJSONTyped,
} from './SubmissionStatusEnum';

/**
 * Reuse full cleaning and validation logic of the models in the REST API.
 * 
 * Reuse ``full_clean()``, ``clean()``, field validation, and uniqueness checks.
 * Also make sure that the pre-filled model instance can be accessed in the DRF view.
 * @export
 * @interface Submission
 */
export interface Submission {
    /**
     * 
     * @type {string}
     * @memberof Submission
     */
    readonly id: string;
    /**
     * 
     * @type {string}
     * @memberof Submission
     */
    challenge: string;
    /**
     * 
     * @type {number}
     * @memberof Submission
     */
    readonly user: number;
    /**
     * 
     * @type {string}
     * @memberof Submission
     */
    zipFile?: string | null;
    /**
     * 
     * @type {SubmissionStatusEnum}
     * @memberof Submission
     */
    readonly status: SubmissionStatusEnum;
    /**
     * 
     * @type {string}
     * @memberof Submission
     */
    readonly feedback: string | null;
    /**
     * 
     * @type {string}
     * @memberof Submission
     */
    readonly xpOutcome: string;
    /**
     * 
     * @type {Array<any>}
     * @memberof Submission
     */
    readonly reflectionAnswers: Array<any> | null;
    /**
     * 
     * @type {Date}
     * @memberof Submission
     */
    readonly submittedAt: Date;
    /**
     * 
     * @type {Date}
     * @memberof Submission
     */
    readonly createdAt: Date | null;
    /**
     * 
     * @type {Date}
     * @memberof Submission
     */
    readonly modifiedAt: Date | null;
}



/**
 * Check if a given object implements the Submission interface.
 */
export function instanceOfSubmission(value: object): value is Submission {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('challenge' in value) || value['challenge'] === undefined) return false;
    if (!('user' in value) || value['user'] === undefined) return false;
    if (!('status' in value) || value['status'] === undefined) return false;
    if (!('feedback' in value) || value['feedback'] === undefined) return false;
    if (!('xpOutcome' in value) || value['xpOutcome'] === undefined) return false;
    if (!('reflectionAnswers' in value) || value['reflectionAnswers'] === undefined) return false;
    if (!('submittedAt' in value) || value['submittedAt'] === undefined) return false;
    if (!('createdAt' in value) || value['createdAt'] === undefined) return false;
    if (!('modifiedAt' in value) || value['modifiedAt'] === undefined) return false;
    return true;
}

export function SubmissionFromJSON(json: any): Submission {
    return SubmissionFromJSONTyped(json, false);
}

export function SubmissionFromJSONTyped(json: any, ignoreDiscriminator: boolean): Submission {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'challenge': json['challenge'],
        'user': json['user'],
        'zipFile': json['zip_file'] == null ? undefined : json['zip_file'],
        'status': SubmissionStatusEnumFromJSON(json['status']),
        'feedback': json['feedback'],
        'xpOutcome': json['xp_outcome'],
        'reflectionAnswers': json['reflection_answers'] == null ? null : json['reflection_answers'],
        'submittedAt': (new Date(json['submitted_at'])),
        'createdAt': (json['created_at'] == null ? null : new Date(json['created_at'])),
        'modifiedAt': (json['modified_at'] == null ? null : new Date(json['modified_at'])),
    };
}

export function SubmissionToJSON(json: any): Submission {
    return SubmissionToJSONTyped(json, false);
}

export function SubmissionToJSONTyped(value?: Omit<Submission, 'id'|'user'|'status'|'feedback'|'xp_outcome'|'reflection_answers'|'submitted_at'|'created_at'|'modified_at'> | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'challenge': value['challenge'],
        'zip_file': value['zipFile'],
    };
}

