/* tslint:disable */
/* eslint-disable */
/**
 * OpenBook API
 * Beautiful and Engaging Learning Materials
 *
 * The version of the OpenAPI document: 0.0.1-pre1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * * `pending` - Pending
 * * `accepted` - Accepted
 * * `rejected` - Rejected
 * @export
 */
export const SubmissionStatusEnum = {
    Pending: 'pending',
    Accepted: 'accepted',
    Rejected: 'rejected'
} as const;
export type SubmissionStatusEnum = typeof SubmissionStatusEnum[keyof typeof SubmissionStatusEnum];


export function instanceOfSubmissionStatusEnum(value: any): boolean {
    for (const key in SubmissionStatusEnum) {
        if (Object.prototype.hasOwnProperty.call(SubmissionStatusEnum, key)) {
            if (SubmissionStatusEnum[key as keyof typeof SubmissionStatusEnum] === value) {
                return true;
            }
        }
    }
    return false;
}

export function SubmissionStatusEnumFromJSON(json: any): SubmissionStatusEnum {
    return SubmissionStatusEnumFromJSONTyped(json, false);
}

export function SubmissionStatusEnumFromJSONTyped(json: any, ignoreDiscriminator: boolean): SubmissionStatusEnum {
    return json as SubmissionStatusEnum;
}

export function SubmissionStatusEnumToJSON(value?: SubmissionStatusEnum | null): any {
    return value as any;
}

export function SubmissionStatusEnumToJSONTyped(value: any, ignoreDiscriminator: boolean): SubmissionStatusEnum {
    return value as SubmissionStatusEnum;
}

