/* tslint:disable */
/* eslint-disable */
/**
 * OpenBook API
 * Beautiful and Engaging Learning Materials
 *
 * The version of the OpenAPI document: 0.0.1-pre1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  PaginatedReflectionQuestionList,
  ReflectionQuestion,
} from '../models/index';
import {
    PaginatedReflectionQuestionListFromJSON,
    PaginatedReflectionQuestionListToJSON,
    ReflectionQuestionFromJSON,
    ReflectionQuestionToJSON,
} from '../models/index';

export interface CodepeatReflectionQuestionsCreateRequest {
    reflectionQuestion: Omit<ReflectionQuestion, 'id'|'created_at'|'modified_at'>;
    expand?: string;
    fields?: string;
    omit?: string;
}

export interface CodepeatReflectionQuestionsDestroyRequest {
    id: string;
    expand?: string;
    fields?: string;
    omit?: string;
}

export interface CodepeatReflectionQuestionsListRequest {
    expand?: string;
    fields?: string;
    omit?: string;
    page?: number;
    pageSize?: number;
    sort?: string;
    challenge?: string;
}

export interface CodepeatReflectionQuestionsRetrieveRequest {
    id: string;
    expand?: string;
    fields?: string;
    omit?: string;
}

/**
 * 
 */
export class CodepeatReflectionQuestionsApi extends runtime.BaseAPI {

    /**
     * Ensure that object permissions are also checked when creating new model instances.  DRF checks object permissions on database-loaded objects, but during creation, the object doesn\'t exist yet. Here we validate the input and construct the instance before saving to allow permission checks.  NOTE: This is a mixin that must be used together with ``ModelViewSet`` to avoid a mysterious circular import in DRF. To overwrite the implementation of ``post()`` the mixin must come first.  Example::      class MyViewSet(ModelViewSetMixin, ModelViewSet):         pass
     * Create
     */
    async codepeatReflectionQuestionsCreateRaw(requestParameters: CodepeatReflectionQuestionsCreateRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ReflectionQuestion>> {
        if (requestParameters['reflectionQuestion'] == null) {
            throw new runtime.RequiredError(
                'reflectionQuestion',
                'Required parameter "reflectionQuestion" was null or undefined when calling codepeatReflectionQuestionsCreate().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['expand'] != null) {
            queryParameters['_expand'] = requestParameters['expand'];
        }

        if (requestParameters['fields'] != null) {
            queryParameters['_fields'] = requestParameters['fields'];
        }

        if (requestParameters['omit'] != null) {
            queryParameters['_omit'] = requestParameters['omit'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["sessionId"] = await this.configuration.apiKey("sessionId"); // SessionAuthentication authentication
        }

        const response = await this.request({
            path: `/api/codepeat/reflection-questions/`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: ReflectionQuestionToJSON(requestParameters['reflectionQuestion']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ReflectionQuestionFromJSON(jsonValue));
    }

    /**
     * Ensure that object permissions are also checked when creating new model instances.  DRF checks object permissions on database-loaded objects, but during creation, the object doesn\'t exist yet. Here we validate the input and construct the instance before saving to allow permission checks.  NOTE: This is a mixin that must be used together with ``ModelViewSet`` to avoid a mysterious circular import in DRF. To overwrite the implementation of ``post()`` the mixin must come first.  Example::      class MyViewSet(ModelViewSetMixin, ModelViewSet):         pass
     * Create
     */
    async codepeatReflectionQuestionsCreate(requestParameters: CodepeatReflectionQuestionsCreateRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ReflectionQuestion> {
        const response = await this.codepeatReflectionQuestionsCreateRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Ensure that object permissions are also checked when creating new model instances.  DRF checks object permissions on database-loaded objects, but during creation, the object doesn\'t exist yet. Here we validate the input and construct the instance before saving to allow permission checks.  NOTE: This is a mixin that must be used together with ``ModelViewSet`` to avoid a mysterious circular import in DRF. To overwrite the implementation of ``post()`` the mixin must come first.  Example::      class MyViewSet(ModelViewSetMixin, ModelViewSet):         pass
     * Delete
     */
    async codepeatReflectionQuestionsDestroyRaw(requestParameters: CodepeatReflectionQuestionsDestroyRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling codepeatReflectionQuestionsDestroy().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['expand'] != null) {
            queryParameters['_expand'] = requestParameters['expand'];
        }

        if (requestParameters['fields'] != null) {
            queryParameters['_fields'] = requestParameters['fields'];
        }

        if (requestParameters['omit'] != null) {
            queryParameters['_omit'] = requestParameters['omit'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["sessionId"] = await this.configuration.apiKey("sessionId"); // SessionAuthentication authentication
        }

        const response = await this.request({
            path: `/api/codepeat/reflection-questions/{id}/`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id']))),
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Ensure that object permissions are also checked when creating new model instances.  DRF checks object permissions on database-loaded objects, but during creation, the object doesn\'t exist yet. Here we validate the input and construct the instance before saving to allow permission checks.  NOTE: This is a mixin that must be used together with ``ModelViewSet`` to avoid a mysterious circular import in DRF. To overwrite the implementation of ``post()`` the mixin must come first.  Example::      class MyViewSet(ModelViewSetMixin, ModelViewSet):         pass
     * Delete
     */
    async codepeatReflectionQuestionsDestroy(requestParameters: CodepeatReflectionQuestionsDestroyRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.codepeatReflectionQuestionsDestroyRaw(requestParameters, initOverrides);
    }

    /**
     * Ensure that object permissions are also checked when creating new model instances.  DRF checks object permissions on database-loaded objects, but during creation, the object doesn\'t exist yet. Here we validate the input and construct the instance before saving to allow permission checks.  NOTE: This is a mixin that must be used together with ``ModelViewSet`` to avoid a mysterious circular import in DRF. To overwrite the implementation of ``post()`` the mixin must come first.  Example::      class MyViewSet(ModelViewSetMixin, ModelViewSet):         pass
     * List
     */
    async codepeatReflectionQuestionsListRaw(requestParameters: CodepeatReflectionQuestionsListRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<PaginatedReflectionQuestionList>> {
        const queryParameters: any = {};

        if (requestParameters['expand'] != null) {
            queryParameters['_expand'] = requestParameters['expand'];
        }

        if (requestParameters['fields'] != null) {
            queryParameters['_fields'] = requestParameters['fields'];
        }

        if (requestParameters['omit'] != null) {
            queryParameters['_omit'] = requestParameters['omit'];
        }

        if (requestParameters['page'] != null) {
            queryParameters['_page'] = requestParameters['page'];
        }

        if (requestParameters['pageSize'] != null) {
            queryParameters['_page_size'] = requestParameters['pageSize'];
        }

        if (requestParameters['sort'] != null) {
            queryParameters['_sort'] = requestParameters['sort'];
        }

        if (requestParameters['challenge'] != null) {
            queryParameters['challenge'] = requestParameters['challenge'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["sessionId"] = await this.configuration.apiKey("sessionId"); // SessionAuthentication authentication
        }

        const response = await this.request({
            path: `/api/codepeat/reflection-questions/`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => PaginatedReflectionQuestionListFromJSON(jsonValue));
    }

    /**
     * Ensure that object permissions are also checked when creating new model instances.  DRF checks object permissions on database-loaded objects, but during creation, the object doesn\'t exist yet. Here we validate the input and construct the instance before saving to allow permission checks.  NOTE: This is a mixin that must be used together with ``ModelViewSet`` to avoid a mysterious circular import in DRF. To overwrite the implementation of ``post()`` the mixin must come first.  Example::      class MyViewSet(ModelViewSetMixin, ModelViewSet):         pass
     * List
     */
    async codepeatReflectionQuestionsList(requestParameters: CodepeatReflectionQuestionsListRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<PaginatedReflectionQuestionList> {
        const response = await this.codepeatReflectionQuestionsListRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Ensure that object permissions are also checked when creating new model instances.  DRF checks object permissions on database-loaded objects, but during creation, the object doesn\'t exist yet. Here we validate the input and construct the instance before saving to allow permission checks.  NOTE: This is a mixin that must be used together with ``ModelViewSet`` to avoid a mysterious circular import in DRF. To overwrite the implementation of ``post()`` the mixin must come first.  Example::      class MyViewSet(ModelViewSetMixin, ModelViewSet):         pass
     * Retrieve
     */
    async codepeatReflectionQuestionsRetrieveRaw(requestParameters: CodepeatReflectionQuestionsRetrieveRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ReflectionQuestion>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling codepeatReflectionQuestionsRetrieve().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['expand'] != null) {
            queryParameters['_expand'] = requestParameters['expand'];
        }

        if (requestParameters['fields'] != null) {
            queryParameters['_fields'] = requestParameters['fields'];
        }

        if (requestParameters['omit'] != null) {
            queryParameters['_omit'] = requestParameters['omit'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["sessionId"] = await this.configuration.apiKey("sessionId"); // SessionAuthentication authentication
        }

        const response = await this.request({
            path: `/api/codepeat/reflection-questions/{id}/`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id']))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ReflectionQuestionFromJSON(jsonValue));
    }

    /**
     * Ensure that object permissions are also checked when creating new model instances.  DRF checks object permissions on database-loaded objects, but during creation, the object doesn\'t exist yet. Here we validate the input and construct the instance before saving to allow permission checks.  NOTE: This is a mixin that must be used together with ``ModelViewSet`` to avoid a mysterious circular import in DRF. To overwrite the implementation of ``post()`` the mixin must come first.  Example::      class MyViewSet(ModelViewSetMixin, ModelViewSet):         pass
     * Retrieve
     */
    async codepeatReflectionQuestionsRetrieve(requestParameters: CodepeatReflectionQuestionsRetrieveRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ReflectionQuestion> {
        const response = await this.codepeatReflectionQuestionsRetrieveRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
