/* tslint:disable */
/* eslint-disable */
/**
 * OpenBook API
 * Beautiful and Engaging Learning Materials
 *
 * The version of the OpenAPI document: 0.0.1-pre1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  PaginatedReflectionList,
  Reflection,
} from '../models/index';
import {
    PaginatedReflectionListFromJSON,
    PaginatedReflectionListToJSON,
    ReflectionFromJSON,
    ReflectionToJSON,
} from '../models/index';

export interface CodepeatReflectionsCreateRequest {
    reflection: Omit<Reflection, 'id'|'created_at'|'modified_at'>;
    expand?: string;
    fields?: string;
    omit?: string;
}

export interface CodepeatReflectionsListRequest {
    expand?: string;
    fields?: string;
    omit?: string;
    page?: number;
    pageSize?: number;
    search?: string;
    sort?: string;
    createdAtDate?: Date;
    createdAtDateGte?: Date;
    createdAtDateLte?: Date;
    submission?: string;
}

export interface CodepeatReflectionsRetrieveRequest {
    id: string;
    expand?: string;
    fields?: string;
    omit?: string;
}

/**
 * 
 */
export class CodepeatReflectionsApi extends runtime.BaseAPI {

    /**
     * Ensure that object permissions are also checked when creating new model instances.  DRF checks object permissions on database-loaded objects, but during creation, the object doesn\'t exist yet. Here we validate the input and construct the instance before saving to allow permission checks.  NOTE: This is a mixin that must be used together with ``ModelViewSet`` to avoid a mysterious circular import in DRF. To overwrite the implementation of ``post()`` the mixin must come first.  Example::      class MyViewSet(ModelViewSetMixin, ModelViewSet):         pass
     * Create
     */
    async codepeatReflectionsCreateRaw(requestParameters: CodepeatReflectionsCreateRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Reflection>> {
        if (requestParameters['reflection'] == null) {
            throw new runtime.RequiredError(
                'reflection',
                'Required parameter "reflection" was null or undefined when calling codepeatReflectionsCreate().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['expand'] != null) {
            queryParameters['_expand'] = requestParameters['expand'];
        }

        if (requestParameters['fields'] != null) {
            queryParameters['_fields'] = requestParameters['fields'];
        }

        if (requestParameters['omit'] != null) {
            queryParameters['_omit'] = requestParameters['omit'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["sessionId"] = await this.configuration.apiKey("sessionId"); // SessionAuthentication authentication
        }

        const response = await this.request({
            path: `/api/codepeat/reflections/`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: ReflectionToJSON(requestParameters['reflection']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ReflectionFromJSON(jsonValue));
    }

    /**
     * Ensure that object permissions are also checked when creating new model instances.  DRF checks object permissions on database-loaded objects, but during creation, the object doesn\'t exist yet. Here we validate the input and construct the instance before saving to allow permission checks.  NOTE: This is a mixin that must be used together with ``ModelViewSet`` to avoid a mysterious circular import in DRF. To overwrite the implementation of ``post()`` the mixin must come first.  Example::      class MyViewSet(ModelViewSetMixin, ModelViewSet):         pass
     * Create
     */
    async codepeatReflectionsCreate(requestParameters: CodepeatReflectionsCreateRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Reflection> {
        const response = await this.codepeatReflectionsCreateRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Ensure that object permissions are also checked when creating new model instances.  DRF checks object permissions on database-loaded objects, but during creation, the object doesn\'t exist yet. Here we validate the input and construct the instance before saving to allow permission checks.  NOTE: This is a mixin that must be used together with ``ModelViewSet`` to avoid a mysterious circular import in DRF. To overwrite the implementation of ``post()`` the mixin must come first.  Example::      class MyViewSet(ModelViewSetMixin, ModelViewSet):         pass
     * List
     */
    async codepeatReflectionsListRaw(requestParameters: CodepeatReflectionsListRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<PaginatedReflectionList>> {
        const queryParameters: any = {};

        if (requestParameters['expand'] != null) {
            queryParameters['_expand'] = requestParameters['expand'];
        }

        if (requestParameters['fields'] != null) {
            queryParameters['_fields'] = requestParameters['fields'];
        }

        if (requestParameters['omit'] != null) {
            queryParameters['_omit'] = requestParameters['omit'];
        }

        if (requestParameters['page'] != null) {
            queryParameters['_page'] = requestParameters['page'];
        }

        if (requestParameters['pageSize'] != null) {
            queryParameters['_page_size'] = requestParameters['pageSize'];
        }

        if (requestParameters['search'] != null) {
            queryParameters['_search'] = requestParameters['search'];
        }

        if (requestParameters['sort'] != null) {
            queryParameters['_sort'] = requestParameters['sort'];
        }

        if (requestParameters['createdAtDate'] != null) {
            queryParameters['created_at__date'] = (requestParameters['createdAtDate'] as any).toISOString().substring(0,10);
        }

        if (requestParameters['createdAtDateGte'] != null) {
            queryParameters['created_at__date__gte'] = (requestParameters['createdAtDateGte'] as any).toISOString().substring(0,10);
        }

        if (requestParameters['createdAtDateLte'] != null) {
            queryParameters['created_at__date__lte'] = (requestParameters['createdAtDateLte'] as any).toISOString().substring(0,10);
        }

        if (requestParameters['submission'] != null) {
            queryParameters['submission'] = requestParameters['submission'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["sessionId"] = await this.configuration.apiKey("sessionId"); // SessionAuthentication authentication
        }

        const response = await this.request({
            path: `/api/codepeat/reflections/`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => PaginatedReflectionListFromJSON(jsonValue));
    }

    /**
     * Ensure that object permissions are also checked when creating new model instances.  DRF checks object permissions on database-loaded objects, but during creation, the object doesn\'t exist yet. Here we validate the input and construct the instance before saving to allow permission checks.  NOTE: This is a mixin that must be used together with ``ModelViewSet`` to avoid a mysterious circular import in DRF. To overwrite the implementation of ``post()`` the mixin must come first.  Example::      class MyViewSet(ModelViewSetMixin, ModelViewSet):         pass
     * List
     */
    async codepeatReflectionsList(requestParameters: CodepeatReflectionsListRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<PaginatedReflectionList> {
        const response = await this.codepeatReflectionsListRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Ensure that object permissions are also checked when creating new model instances.  DRF checks object permissions on database-loaded objects, but during creation, the object doesn\'t exist yet. Here we validate the input and construct the instance before saving to allow permission checks.  NOTE: This is a mixin that must be used together with ``ModelViewSet`` to avoid a mysterious circular import in DRF. To overwrite the implementation of ``post()`` the mixin must come first.  Example::      class MyViewSet(ModelViewSetMixin, ModelViewSet):         pass
     * Retrieve
     */
    async codepeatReflectionsRetrieveRaw(requestParameters: CodepeatReflectionsRetrieveRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Reflection>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling codepeatReflectionsRetrieve().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['expand'] != null) {
            queryParameters['_expand'] = requestParameters['expand'];
        }

        if (requestParameters['fields'] != null) {
            queryParameters['_fields'] = requestParameters['fields'];
        }

        if (requestParameters['omit'] != null) {
            queryParameters['_omit'] = requestParameters['omit'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["sessionId"] = await this.configuration.apiKey("sessionId"); // SessionAuthentication authentication
        }

        const response = await this.request({
            path: `/api/codepeat/reflections/{id}/`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id']))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ReflectionFromJSON(jsonValue));
    }

    /**
     * Ensure that object permissions are also checked when creating new model instances.  DRF checks object permissions on database-loaded objects, but during creation, the object doesn\'t exist yet. Here we validate the input and construct the instance before saving to allow permission checks.  NOTE: This is a mixin that must be used together with ``ModelViewSet`` to avoid a mysterious circular import in DRF. To overwrite the implementation of ``post()`` the mixin must come first.  Example::      class MyViewSet(ModelViewSetMixin, ModelViewSet):         pass
     * Retrieve
     */
    async codepeatReflectionsRetrieve(requestParameters: CodepeatReflectionsRetrieveRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Reflection> {
        const response = await this.codepeatReflectionsRetrieveRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
