/* tslint:disable */
/* eslint-disable */
/**
 * OpenBook API
 * Beautiful and Engaging Learning Materials
 *
 * The version of the OpenAPI document: 0.0.1-pre1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  Challenge,
  ChallengeCanCreate,
  ChallengeInviteLink,
  ChallengeUnlock,
  ChallengeUnlockResult,
  PaginatedChallengeList,
  PatchedChallenge,
} from '../models/index';
import {
    ChallengeFromJSON,
    ChallengeToJSON,
    ChallengeCanCreateFromJSON,
    ChallengeCanCreateToJSON,
    ChallengeInviteLinkFromJSON,
    ChallengeInviteLinkToJSON,
    ChallengeUnlockFromJSON,
    ChallengeUnlockToJSON,
    ChallengeUnlockResultFromJSON,
    ChallengeUnlockResultToJSON,
    PaginatedChallengeListFromJSON,
    PaginatedChallengeListToJSON,
    PatchedChallengeFromJSON,
    PatchedChallengeToJSON,
} from '../models/index';

export interface CodepeatChallengesCanCreateRetrieveRequest {
    expand?: string;
    fields?: string;
    omit?: string;
}

export interface CodepeatChallengesCreateRequest {
    challenge: Omit<Challenge, 'id'|'views'|'created_by'|'created_at'|'modified_at'>;
    expand?: string;
    fields?: string;
    omit?: string;
}

export interface CodepeatChallengesDestroyRequest {
    id: string;
    expand?: string;
    fields?: string;
    omit?: string;
}

export interface CodepeatChallengesInviteLinkCreateRequest {
    id: string;
    expand?: string;
    fields?: string;
    omit?: string;
}

export interface CodepeatChallengesListRequest {
    expand?: string;
    fields?: string;
    omit?: string;
    page?: number;
    pageSize?: number;
    search?: string;
    sort?: string;
    course?: string;
    createdBy?: number;
    difficulty?: CodepeatChallengesListDifficultyEnum;
    type?: CodepeatChallengesListTypeEnum;
    visibility?: CodepeatChallengesListVisibilityEnum;
}

export interface CodepeatChallengesPartialUpdateRequest {
    id: string;
    expand?: string;
    fields?: string;
    omit?: string;
    patchedChallenge?: Omit<PatchedChallenge, 'id'|'views'|'created_by'|'created_at'|'modified_at'>;
}

export interface CodepeatChallengesRetrieveRequest {
    id: string;
    expand?: string;
    fields?: string;
    omit?: string;
}

export interface CodepeatChallengesUnlockCreateRequest {
    challengeUnlock: ChallengeUnlock;
    expand?: string;
    fields?: string;
    omit?: string;
}

export interface CodepeatChallengesUpdateRequest {
    id: string;
    challenge: Omit<Challenge, 'id'|'views'|'created_by'|'created_at'|'modified_at'>;
    expand?: string;
    fields?: string;
    omit?: string;
}

/**
 * 
 */
export class CodepeatChallengesApi extends runtime.BaseAPI {

    /**
     * Report whether the requesting user may create challenges (teacher or admin).
     * Retrieve
     */
    async codepeatChallengesCanCreateRetrieveRaw(requestParameters: CodepeatChallengesCanCreateRetrieveRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ChallengeCanCreate>> {
        const queryParameters: any = {};

        if (requestParameters['expand'] != null) {
            queryParameters['_expand'] = requestParameters['expand'];
        }

        if (requestParameters['fields'] != null) {
            queryParameters['_fields'] = requestParameters['fields'];
        }

        if (requestParameters['omit'] != null) {
            queryParameters['_omit'] = requestParameters['omit'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["sessionId"] = await this.configuration.apiKey("sessionId"); // SessionAuthentication authentication
        }

        const response = await this.request({
            path: `/api/codepeat/challenges/can-create/`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ChallengeCanCreateFromJSON(jsonValue));
    }

    /**
     * Report whether the requesting user may create challenges (teacher or admin).
     * Retrieve
     */
    async codepeatChallengesCanCreateRetrieve(requestParameters: CodepeatChallengesCanCreateRetrieveRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ChallengeCanCreate> {
        const response = await this.codepeatChallengesCanCreateRetrieveRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Allow unrestricted access to the ``list`` and ``retrieve`` actions.  This small view set mixin class allows unrestricted access to the ``list`` and ``retrieve`` actions while deferring permission checks for all other actions to the permission classes of the view set (usually defined in ``settings.py``).
     * Create
     */
    async codepeatChallengesCreateRaw(requestParameters: CodepeatChallengesCreateRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Challenge>> {
        if (requestParameters['challenge'] == null) {
            throw new runtime.RequiredError(
                'challenge',
                'Required parameter "challenge" was null or undefined when calling codepeatChallengesCreate().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['expand'] != null) {
            queryParameters['_expand'] = requestParameters['expand'];
        }

        if (requestParameters['fields'] != null) {
            queryParameters['_fields'] = requestParameters['fields'];
        }

        if (requestParameters['omit'] != null) {
            queryParameters['_omit'] = requestParameters['omit'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["sessionId"] = await this.configuration.apiKey("sessionId"); // SessionAuthentication authentication
        }

        const response = await this.request({
            path: `/api/codepeat/challenges/`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: ChallengeToJSON(requestParameters['challenge']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ChallengeFromJSON(jsonValue));
    }

    /**
     * Allow unrestricted access to the ``list`` and ``retrieve`` actions.  This small view set mixin class allows unrestricted access to the ``list`` and ``retrieve`` actions while deferring permission checks for all other actions to the permission classes of the view set (usually defined in ``settings.py``).
     * Create
     */
    async codepeatChallengesCreate(requestParameters: CodepeatChallengesCreateRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Challenge> {
        const response = await this.codepeatChallengesCreateRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Allow unrestricted access to the ``list`` and ``retrieve`` actions.  This small view set mixin class allows unrestricted access to the ``list`` and ``retrieve`` actions while deferring permission checks for all other actions to the permission classes of the view set (usually defined in ``settings.py``).
     * Delete
     */
    async codepeatChallengesDestroyRaw(requestParameters: CodepeatChallengesDestroyRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling codepeatChallengesDestroy().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['expand'] != null) {
            queryParameters['_expand'] = requestParameters['expand'];
        }

        if (requestParameters['fields'] != null) {
            queryParameters['_fields'] = requestParameters['fields'];
        }

        if (requestParameters['omit'] != null) {
            queryParameters['_omit'] = requestParameters['omit'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["sessionId"] = await this.configuration.apiKey("sessionId"); // SessionAuthentication authentication
        }

        const response = await this.request({
            path: `/api/codepeat/challenges/{id}/`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id']))),
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Allow unrestricted access to the ``list`` and ``retrieve`` actions.  This small view set mixin class allows unrestricted access to the ``list`` and ``retrieve`` actions while deferring permission checks for all other actions to the permission classes of the view set (usually defined in ``settings.py``).
     * Delete
     */
    async codepeatChallengesDestroy(requestParameters: CodepeatChallengesDestroyRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.codepeatChallengesDestroyRaw(requestParameters, initOverrides);
    }

    /**
     * Create a fresh, time-limited invitation link for a private challenge (creator only).
     * Create
     */
    async codepeatChallengesInviteLinkCreateRaw(requestParameters: CodepeatChallengesInviteLinkCreateRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ChallengeInviteLink>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling codepeatChallengesInviteLinkCreate().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['expand'] != null) {
            queryParameters['_expand'] = requestParameters['expand'];
        }

        if (requestParameters['fields'] != null) {
            queryParameters['_fields'] = requestParameters['fields'];
        }

        if (requestParameters['omit'] != null) {
            queryParameters['_omit'] = requestParameters['omit'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["sessionId"] = await this.configuration.apiKey("sessionId"); // SessionAuthentication authentication
        }

        const response = await this.request({
            path: `/api/codepeat/challenges/{id}/invite-link/`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id']))),
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ChallengeInviteLinkFromJSON(jsonValue));
    }

    /**
     * Create a fresh, time-limited invitation link for a private challenge (creator only).
     * Create
     */
    async codepeatChallengesInviteLinkCreate(requestParameters: CodepeatChallengesInviteLinkCreateRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ChallengeInviteLink> {
        const response = await this.codepeatChallengesInviteLinkCreateRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Allow unrestricted access to the ``list`` and ``retrieve`` actions.  This small view set mixin class allows unrestricted access to the ``list`` and ``retrieve`` actions while deferring permission checks for all other actions to the permission classes of the view set (usually defined in ``settings.py``).
     * List
     */
    async codepeatChallengesListRaw(requestParameters: CodepeatChallengesListRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<PaginatedChallengeList>> {
        const queryParameters: any = {};

        if (requestParameters['expand'] != null) {
            queryParameters['_expand'] = requestParameters['expand'];
        }

        if (requestParameters['fields'] != null) {
            queryParameters['_fields'] = requestParameters['fields'];
        }

        if (requestParameters['omit'] != null) {
            queryParameters['_omit'] = requestParameters['omit'];
        }

        if (requestParameters['page'] != null) {
            queryParameters['_page'] = requestParameters['page'];
        }

        if (requestParameters['pageSize'] != null) {
            queryParameters['_page_size'] = requestParameters['pageSize'];
        }

        if (requestParameters['search'] != null) {
            queryParameters['_search'] = requestParameters['search'];
        }

        if (requestParameters['sort'] != null) {
            queryParameters['_sort'] = requestParameters['sort'];
        }

        if (requestParameters['course'] != null) {
            queryParameters['course'] = requestParameters['course'];
        }

        if (requestParameters['createdBy'] != null) {
            queryParameters['created_by'] = requestParameters['createdBy'];
        }

        if (requestParameters['difficulty'] != null) {
            queryParameters['difficulty'] = requestParameters['difficulty'];
        }

        if (requestParameters['type'] != null) {
            queryParameters['type'] = requestParameters['type'];
        }

        if (requestParameters['visibility'] != null) {
            queryParameters['visibility'] = requestParameters['visibility'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["sessionId"] = await this.configuration.apiKey("sessionId"); // SessionAuthentication authentication
        }

        const response = await this.request({
            path: `/api/codepeat/challenges/`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => PaginatedChallengeListFromJSON(jsonValue));
    }

    /**
     * Allow unrestricted access to the ``list`` and ``retrieve`` actions.  This small view set mixin class allows unrestricted access to the ``list`` and ``retrieve`` actions while deferring permission checks for all other actions to the permission classes of the view set (usually defined in ``settings.py``).
     * List
     */
    async codepeatChallengesList(requestParameters: CodepeatChallengesListRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<PaginatedChallengeList> {
        const response = await this.codepeatChallengesListRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Allow unrestricted access to the ``list`` and ``retrieve`` actions.  This small view set mixin class allows unrestricted access to the ``list`` and ``retrieve`` actions while deferring permission checks for all other actions to the permission classes of the view set (usually defined in ``settings.py``).
     * Partial Update
     */
    async codepeatChallengesPartialUpdateRaw(requestParameters: CodepeatChallengesPartialUpdateRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Challenge>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling codepeatChallengesPartialUpdate().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['expand'] != null) {
            queryParameters['_expand'] = requestParameters['expand'];
        }

        if (requestParameters['fields'] != null) {
            queryParameters['_fields'] = requestParameters['fields'];
        }

        if (requestParameters['omit'] != null) {
            queryParameters['_omit'] = requestParameters['omit'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["sessionId"] = await this.configuration.apiKey("sessionId"); // SessionAuthentication authentication
        }

        const response = await this.request({
            path: `/api/codepeat/challenges/{id}/`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id']))),
            method: 'PATCH',
            headers: headerParameters,
            query: queryParameters,
            body: PatchedChallengeToJSON(requestParameters['patchedChallenge']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ChallengeFromJSON(jsonValue));
    }

    /**
     * Allow unrestricted access to the ``list`` and ``retrieve`` actions.  This small view set mixin class allows unrestricted access to the ``list`` and ``retrieve`` actions while deferring permission checks for all other actions to the permission classes of the view set (usually defined in ``settings.py``).
     * Partial Update
     */
    async codepeatChallengesPartialUpdate(requestParameters: CodepeatChallengesPartialUpdateRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Challenge> {
        const response = await this.codepeatChallengesPartialUpdateRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Allow unrestricted access to the ``list`` and ``retrieve`` actions.  This small view set mixin class allows unrestricted access to the ``list`` and ``retrieve`` actions while deferring permission checks for all other actions to the permission classes of the view set (usually defined in ``settings.py``).
     * Retrieve
     */
    async codepeatChallengesRetrieveRaw(requestParameters: CodepeatChallengesRetrieveRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Challenge>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling codepeatChallengesRetrieve().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['expand'] != null) {
            queryParameters['_expand'] = requestParameters['expand'];
        }

        if (requestParameters['fields'] != null) {
            queryParameters['_fields'] = requestParameters['fields'];
        }

        if (requestParameters['omit'] != null) {
            queryParameters['_omit'] = requestParameters['omit'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["sessionId"] = await this.configuration.apiKey("sessionId"); // SessionAuthentication authentication
        }

        const response = await this.request({
            path: `/api/codepeat/challenges/{id}/`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id']))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ChallengeFromJSON(jsonValue));
    }

    /**
     * Allow unrestricted access to the ``list`` and ``retrieve`` actions.  This small view set mixin class allows unrestricted access to the ``list`` and ``retrieve`` actions while deferring permission checks for all other actions to the permission classes of the view set (usually defined in ``settings.py``).
     * Retrieve
     */
    async codepeatChallengesRetrieve(requestParameters: CodepeatChallengesRetrieveRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Challenge> {
        const response = await this.codepeatChallengesRetrieveRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Redeem an invitation link: grant the signed-in user permanent access to the challenge.
     * Create
     */
    async codepeatChallengesUnlockCreateRaw(requestParameters: CodepeatChallengesUnlockCreateRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ChallengeUnlockResult>> {
        if (requestParameters['challengeUnlock'] == null) {
            throw new runtime.RequiredError(
                'challengeUnlock',
                'Required parameter "challengeUnlock" was null or undefined when calling codepeatChallengesUnlockCreate().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['expand'] != null) {
            queryParameters['_expand'] = requestParameters['expand'];
        }

        if (requestParameters['fields'] != null) {
            queryParameters['_fields'] = requestParameters['fields'];
        }

        if (requestParameters['omit'] != null) {
            queryParameters['_omit'] = requestParameters['omit'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["sessionId"] = await this.configuration.apiKey("sessionId"); // SessionAuthentication authentication
        }

        const response = await this.request({
            path: `/api/codepeat/challenges/unlock/`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: ChallengeUnlockToJSON(requestParameters['challengeUnlock']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ChallengeUnlockResultFromJSON(jsonValue));
    }

    /**
     * Redeem an invitation link: grant the signed-in user permanent access to the challenge.
     * Create
     */
    async codepeatChallengesUnlockCreate(requestParameters: CodepeatChallengesUnlockCreateRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ChallengeUnlockResult> {
        const response = await this.codepeatChallengesUnlockCreateRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Allow unrestricted access to the ``list`` and ``retrieve`` actions.  This small view set mixin class allows unrestricted access to the ``list`` and ``retrieve`` actions while deferring permission checks for all other actions to the permission classes of the view set (usually defined in ``settings.py``).
     * Update
     */
    async codepeatChallengesUpdateRaw(requestParameters: CodepeatChallengesUpdateRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Challenge>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling codepeatChallengesUpdate().'
            );
        }

        if (requestParameters['challenge'] == null) {
            throw new runtime.RequiredError(
                'challenge',
                'Required parameter "challenge" was null or undefined when calling codepeatChallengesUpdate().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['expand'] != null) {
            queryParameters['_expand'] = requestParameters['expand'];
        }

        if (requestParameters['fields'] != null) {
            queryParameters['_fields'] = requestParameters['fields'];
        }

        if (requestParameters['omit'] != null) {
            queryParameters['_omit'] = requestParameters['omit'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["sessionId"] = await this.configuration.apiKey("sessionId"); // SessionAuthentication authentication
        }

        const response = await this.request({
            path: `/api/codepeat/challenges/{id}/`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id']))),
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
            body: ChallengeToJSON(requestParameters['challenge']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ChallengeFromJSON(jsonValue));
    }

    /**
     * Allow unrestricted access to the ``list`` and ``retrieve`` actions.  This small view set mixin class allows unrestricted access to the ``list`` and ``retrieve`` actions while deferring permission checks for all other actions to the permission classes of the view set (usually defined in ``settings.py``).
     * Update
     */
    async codepeatChallengesUpdate(requestParameters: CodepeatChallengesUpdateRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Challenge> {
        const response = await this.codepeatChallengesUpdateRaw(requestParameters, initOverrides);
        return await response.value();
    }

}

/**
 * @export
 */
export const CodepeatChallengesListDifficultyEnum = {
    Easy: 'easy',
    Hard: 'hard',
    Medium: 'medium'
} as const;
export type CodepeatChallengesListDifficultyEnum = typeof CodepeatChallengesListDifficultyEnum[keyof typeof CodepeatChallengesListDifficultyEnum];
/**
 * @export
 */
export const CodepeatChallengesListTypeEnum = {
    Group: 'group',
    Solo: 'solo'
} as const;
export type CodepeatChallengesListTypeEnum = typeof CodepeatChallengesListTypeEnum[keyof typeof CodepeatChallengesListTypeEnum];
/**
 * @export
 */
export const CodepeatChallengesListVisibilityEnum = {
    Private: 'private',
    Public: 'public'
} as const;
export type CodepeatChallengesListVisibilityEnum = typeof CodepeatChallengesListVisibilityEnum[keyof typeof CodepeatChallengesListVisibilityEnum];
